/**
 * 注音符號聲辨挑戰賽 - 題庫資料庫 (Bopomofo Database)
 */

const BOPOMOFO_DATA = [
  // --- 聲母 Initials ---
{ symbol: 'ㄅ', pinyin: 'b', name: 'ㄅㄛ (bō)', category: 'initial', example: '包', phrase: '包子的包', hint: '英語中的 "b"（如 boy）' },
{ symbol: 'ㄆ', pinyin: 'p', name: 'ㄆㄛ (pō)', category: 'initial', example: '婆', phrase: '外婆的婆', hint: '英語中的 "p"（送氣，如 pear）' },
{ symbol: 'ㄇ', pinyin: 'm', name: 'ㄇㄛ (mō)', category: 'initial', example: '貓', phrase: '貓咪的貓', hint: '英語中的 "m"（如 cat）' },
{ symbol: 'ㄈ', pinyin: 'f', name: 'ㄈㄛ (fō)', category: 'initial', example: '飛', phrase: '飛機的飛', hint: '英語中的 "f"（如 fly）' },
{ symbol: 'ㄉ', pinyin: 'd', name: 'ㄉㄜ (dē)', category: 'initial', example: '地', phrase: '土地的地', hint: '英語中的 "d"（如 dog）' },
{ symbol: 'ㄊ', pinyin: 't', name: 'ㄊㄜ (tē)', category: 'initial', example: '天', phrase: '天空的天', hint: '英語中的 "t"（送氣，如 toy）' },
{ symbol: 'ㄋ', pinyin: 'n', name: 'ㄋㄜ (nē)', category: 'initial', example: '牛', phrase: '黃牛的牛', hint: '英語中的 "n"（如 no）' },
{ symbol: 'ㄌ', pinyin: 'l', name: 'ㄌㄜ (lē)', category: 'initial', example: '老', phrase: '老師的老', hint: '英語中的 "l"（如 love）' },
{ symbol: 'ㄍ', pinyin: 'g', name: 'ㄍㄜ (gē)', category: 'initial', example: '狗', phrase: '小狗的狗', hint: '英語中的 "g"（不送氣，如 go）' },
{ symbol: 'ㄎ', pinyin: 'k', name: 'ㄎㄜ (kē)', category: 'initial', example: '開', phrase: '開門的開', hint: '英語中的 "k"（送氣，如 key）' },
{ symbol: 'ㄏ', pinyin: 'h', name: 'ㄏㄜ (hē)', category: 'initial', example: '花', phrase: '花朵的花', hint: '英語中的 "h"（如 hat）' },
{ symbol: 'ㄐ', pinyin: 'j', name: 'ㄐㄧ (jī)', category: 'initial', example: '雞', phrase: '小雞的雞', hint: '英語中的 "j"（不送氣，舌面音，如 jeep）' },
{ symbol: 'ㄑ', pinyin: 'q', name: 'ㄑㄧ (qī)', category: 'initial', example: '七', phrase: '數字七的七', hint: '類似英語 "ch"（送氣，舌面音，如 cheap）' },
{ symbol: 'ㄒ', pinyin: 'x', name: 'ㄒㄧ (xī)', category: 'initial', example: '西', phrase: '西瓜的西', hint: '類似英語 "sh"（舌面音，如 she）' },
{ symbol: 'ㄓ', pinyin: 'zh', name: 'ㄓ (zhī)', category: 'initial', example: '豬', phrase: '小豬的豬', hint: '捲舌音 "zh"（不送氣，如 jury）' },
{ symbol: 'ㄔ', pinyin: 'ch', name: 'ㄔ (chī)', category: 'initial', example: '車', phrase: '汽車的車', hint: '捲舌音 "ch"（送氣，如 church）' },
{ symbol: 'ㄕ', pinyin: 'sh', name: 'ㄕ (shī)', category: 'initial', example: '書', phrase: '看書的書', hint: '捲舌音 "sh"（如 shoe）' },
{ symbol: 'ㄖ', pinyin: 'r', name: 'ㄖ (rì)', category: 'initial', example: '日', phrase: '日期的日', hint: '捲舌音 "r"（如 raw）' },
{ symbol: 'ㄗ', pinyin: 'z', name: 'ㄗ (zī)', category: 'initial', example: '字', phrase: '寫字的字', hint: '平舌音 "z"（不送氣，如 kids 中的 ds）' },
{ symbol: 'ㄘ', pinyin: 'c', name: 'ㄘ (cī)', category: 'initial', example: '詞', phrase: '造詞的詞', hint: '平舌音 "ts"（送氣，如 cats 中的 ts）' },
{ symbol: 'ㄙ', pinyin: 's', name: 'ㄙ (sī)', category: 'initial', example: '四', phrase: '數字四的四', hint: '平舌音 "s"（如 say）' },
  { symbol: 'ㄅ', pinyin: 'b', name: 'ㄅㄛ (bō)', category: 'initial', example: '爸', phrase: '爸爸的爸', hint: '英語中的 "b"（如 boy）' },
  { symbol: 'ㄅ', pinyin: 'b', name: 'ㄅㄛ (bō)', category: 'initial', example: '筆', phrase: '鉛筆的筆', hint: '英語中的 "b"（如 boy）' },
  { symbol: 'ㄆ', pinyin: 'p', name: 'ㄆㄛ (pō)', category: 'initial', example: '配', phrase: '配合的配', hint: '英語中的 "p"（送氣，如 pear）' },
  { symbol: 'ㄆ', pinyin: 'p', name: 'ㄆㄛ (pō)', category: 'initial', example: '跑', phrase: '跑步的跑', hint: '英語中的 "p"（送氣，如 pear）' },
  { symbol: 'ㄇ', pinyin: 'm', name: 'ㄇㄛ (mō)', category: 'initial', example: '門', phrase: '大門的門', hint: '英語中的 "m"（如 cat）' },
  { symbol: 'ㄇ', pinyin: 'm', name: 'ㄇㄛ (mō)', category: 'initial', example: '買', phrase: '買東西的買', hint: '英語中的 "m"（如 cat）' },
  { symbol: 'ㄈ', pinyin: 'f', name: 'ㄈㄛ (fō)', category: 'initial', example: '風', phrase: '颳風的風', hint: '英語中的 "f"（如 fly）' },
  { symbol: 'ㄈ', pinyin: 'f', name: 'ㄈㄛ (fō)', category: 'initial', example: '放', phrase: '放學的放', hint: '英語中的 "f"（如 fly）' },
  { symbol: 'ㄉ', pinyin: 'd', name: 'ㄉㄜ (dē)', category: 'initial', example: '刀', phrase: '剪刀的刀', hint: '英語中的 "d"（如 dog）' },
  { symbol: 'ㄉ', pinyin: 'd', name: 'ㄉㄜ (dē)', category: 'initial', example: '讀', phrase: '讀書的讀', hint: '英語中的 "d"（如 dog）' },
  { symbol: 'ㄊ', pinyin: 't', name: 'ㄊㄜ (tē)', category: 'initial', example: '糖', phrase: '糖果的糖', hint: '英語中的 "t"（送氣，如 toy）' },
  { symbol: 'ㄊ', pinyin: 't', name: 'ㄊㄜ (tē)', category: 'initial', example: '跳', phrase: '跳舞的跳', hint: '英語中的 "t"（送氣，如 toy）' },
  { symbol: 'ㄋ', pinyin: 'n', name: 'ㄋㄜ (nē)', category: 'initial', example: '腦', phrase: '電腦的腦', hint: '英語中的 "n"（如 no）' },
  { symbol: 'ㄋ', pinyin: 'n', name: 'ㄋㄜ (nē)', category: 'initial', example: '拿', phrase: '拿筆的拿', hint: '英語中的 "n"（如 no）' },
  { symbol: 'ㄌ', pinyin: 'l', name: 'ㄌㄜ (lē)', category: 'initial', example: '綠', phrase: '綠色的綠', hint: '英語中的 "l"（如 love）' },
  { symbol: 'ㄌ', pinyin: 'l', name: 'ㄌㄜ (lē)', category: 'initial', example: '藍', phrase: '藍色的藍', hint: '英語中的 "l"（如 love）' },
  { symbol: 'ㄍ', pinyin: 'g', name: 'ㄍㄜ (gē)', category: 'initial', example: '歌', phrase: '唱歌的歌', hint: '英語中的 "g"（不送氣，如 go）' },
  { symbol: 'ㄍ', pinyin: 'g', name: 'ㄍㄜ (gē)', category: 'initial', example: '高', phrase: '高山的高', hint: '英語中的 "g"（不送氣，如 go）' },
  { symbol: 'ㄎ', pinyin: 'k', name: 'ㄎㄜ (kē)', category: 'initial', example: '看', phrase: '看書的看', hint: '英語中的 "k"（送氣，如 key）' },
  { symbol: 'ㄎ', pinyin: 'k', name: 'ㄎㄜ (kē)', category: 'initial', example: '哭', phrase: '哭泣的哭', hint: '英語中的 "k"（送氣，如 key）' },
  { symbol: 'ㄏ', pinyin: 'h', name: 'ㄏㄜ (hē)', category: 'initial', example: '海', phrase: '大海的海', hint: '英語中的 "h"（如 hat）' },
  { symbol: 'ㄏ', pinyin: 'h', name: 'ㄏㄜ (hē)', category: 'initial', example: '紅', phrase: '紅色的紅', hint: '英語中的 "h"（如 hat）' },
  { symbol: 'ㄐ', pinyin: 'j', name: 'ㄐㄧ (jī)', category: 'initial', example: '家', phrase: '國家的家', hint: '英語中的 "j"（不送氣，舌面音，如 jeep）' },
  { symbol: 'ㄐ', pinyin: 'j', name: 'ㄐㄧ (jī)', category: 'initial', example: '腳', phrase: '雙腳的腳', hint: '英語中的 "j"（不送氣，舌面音，如 jeep）' },
  { symbol: 'ㄑ', pinyin: 'q', name: 'ㄑㄧ (qī)', category: 'initial', example: '去', phrase: '來去的去', hint: '類似英語 "ch"（送氣，舌面音，如 cheap）' },
  { symbol: 'ㄑ', pinyin: 'q', name: 'ㄑㄧ (qī)', category: 'initial', example: '氣', phrase: '天氣的氣', hint: '類似英語 "ch"（送氣，舌面音，如 cheap）' },
  { symbol: 'ㄒ', pinyin: 'x', name: 'ㄒㄧ (xī)', category: 'initial', example: '洗', phrase: '洗衣服的洗', hint: '類似英語 "sh"（舌面音，如 she）' },
  { symbol: 'ㄒ', pinyin: 'x', name: 'ㄒㄧ (xī)', category: 'initial', example: '星', phrase: '星星的星', hint: '類似英語 "sh"（舌面音，如 she）' },
  { symbol: 'ㄓ', pinyin: 'zh', name: 'ㄓ (zhī)', category: 'initial', example: '紙', phrase: '衛生紙的紙', hint: '捲舌音 "zh"（不送氣，如 jury）' },
  { symbol: 'ㄓ', pinyin: 'zh', name: 'ㄓ (zhī)', category: 'initial', example: '針', phrase: '指南針的針', hint: '捲舌音 "zh"（不送氣，如 jury）' },
  { symbol: 'ㄔ', pinyin: 'ch', name: 'ㄔ (chī)', category: 'initial', example: '吃', phrase: '吃東西的吃', hint: '捲舌音 "ch"（送氣，如 church）' },
  { symbol: 'ㄔ', pinyin: 'ch', name: 'ㄔ (chī)', category: 'initial', example: '尺', phrase: '尺子的尺', hint: '捲舌音 "ch"（送氣，如 church）' },
  { symbol: 'ㄕ', pinyin: 'sh', name: 'ㄕ (shī)', category: 'initial', example: '手', phrase: '雙手的手', hint: '捲舌音 "sh"（如 shoe）' },
  { symbol: 'ㄕ', pinyin: 'sh', name: 'ㄕ (shī)', category: 'initial', example: '水', phrase: '水果的水', hint: '捲舌音 "sh"（如 shoe）' },
  { symbol: 'ㄖ', pinyin: 'r', name: 'ㄖ (rì)', category: 'initial', example: '熱', phrase: '熱狗的熱', hint: '捲舌音 "r"（如 raw）' },
  { symbol: 'ㄖ', pinyin: 'r', name: 'ㄖ (rì)', category: 'initial', example: '肉', phrase: '牛肉的肉', hint: '捲舌音 "r"（如 raw）' },
  { symbol: 'ㄗ', pinyin: 'z', name: 'ㄗ (zī)', category: 'initial', example: '走', phrase: '走路的走', hint: '平舌音 "z"（不送氣，如 kids 中的 ds）' },
  { symbol: 'ㄗ', pinyin: 'z', name: 'ㄗ (zī)', category: 'initial', example: '早', phrase: '早安的早', hint: '平舌音 "z"（不送氣，如 kids 中的 ds）' },
  { symbol: 'ㄘ', pinyin: 'c', name: 'ㄘ (cī)', category: 'initial', example: '草', phrase: '草地的草', hint: '平舌音 "ts"（送氣，如 cats 中的 ts）' },
  { symbol: 'ㄘ', pinyin: 'c', name: 'ㄘ (cī)', category: 'initial', example: '餐', phrase: '餐廳的餐', hint: '平舌音 "ts"（送氣，如 cats 中的 ts）' },
  { symbol: 'ㄙ', pinyin: 's', name: 'ㄙ (sī)', category: 'initial', example: '送', phrase: '送禮的送', hint: '平舌音 "s"（如 say）' },
  { symbol: 'ㄙ', pinyin: 's', name: 'ㄙ (sī)', category: 'initial', example: '色', phrase: '紅色的色', hint: '平舌音 "s"（如 say）' },

  // --- 介母 Medials ---
{ symbol: 'ㄧ', pinyin: 'i/y', name: 'ㄧ (yī)', category: 'medial', example: '衣', phrase: '衣服的衣', hint: '漢語拼音 i，英語中的 "ee"（如 meet）' },
{ symbol: 'ㄨ', pinyin: 'u/w', name: 'ㄨ (wū)', category: 'medial', example: '屋', phrase: '房屋的屋', hint: '漢語拼音 u，英語中的 "oo"（如 boot）' },
{ symbol: 'ㄩ', pinyin: 'yu/v', name: 'ㄩ (yū)', category: 'medial', example: '雨', phrase: '下雨的雨', hint: '德語的 "ü" 或法語的 "u"' },
  { symbol: 'ㄧ', pinyin: 'i/y', name: 'ㄧ (yī)', category: 'medial', example: '椅', phrase: '椅子的椅', hint: '漢語拼音 i，英語中的 "ee"（如 meet）' },
  { symbol: 'ㄧ', pinyin: 'i/y', name: 'ㄧ (yī)', category: 'medial', example: '醫', phrase: '醫生的醫', hint: '漢語拼音 i，英語中的 "ee"（如 meet）' },
  { symbol: 'ㄨ', pinyin: 'u/w', name: 'ㄨ (wū)', category: 'medial', example: '五', phrase: '數字五的五', hint: '漢語拼音 u，英語中的 "oo"（如 boot）' },
  { symbol: 'ㄨ', pinyin: 'u/w', name: 'ㄨ (wū)', category: 'medial', example: '玩', phrase: '玩具的玩', hint: '漢語拼音 u，英語中的 "oo"（如 boot）' },
  { symbol: 'ㄩ', pinyin: 'yu/v', name: 'ㄩ (yū)', category: 'medial', example: '魚', phrase: '小魚的魚', hint: '德語的 "ü" 或法語的 "u"' },
  { symbol: 'ㄩ', pinyin: 'yu/v', name: 'ㄩ (yū)', category: 'medial', example: '雲', phrase: '白雲的雲', hint: '德語的 "ü" 或法語的 "u"' },

  // --- 韻母 Finals ---
{ symbol: 'ㄚ', pinyin: 'a', name: 'ㄚ (ā)', category: 'final', example: '鴨', phrase: '鴨子的鴨', hint: '英語中的 "a"（如 father）' },
{ symbol: 'ㄛ', pinyin: 'o', name: 'ㄛ (ō)', category: 'final', example: '喔', phrase: '喔喔叫的喔', hint: '英語中的 "aw"（如 law）' },
{ symbol: 'ㄜ', pinyin: 'e', name: 'ㄜ (ē)', category: 'final', example: '鵝', phrase: '白鵝的鵝', hint: '發音介於 "uh" 與 "eh" 之間（如 up）' },
{ symbol: 'ㄝ', pinyin: 'eh', name: 'ㄝ (ê)', category: 'final', example: '椰', phrase: '椰子的椰', hint: '英語中的 "e"（如 yes 中的 ye）' },
{ symbol: 'ㄞ', pinyin: 'ai', name: 'ㄞ (āi)', category: 'final', example: '愛', phrase: '愛心的愛', hint: '英語中的 "eye"（如 fly 中的 y）' },
{ symbol: 'ㄟ', pinyin: 'ei', name: 'ㄟ (ēi)', category: 'final', example: '誒', phrase: '誒唷的誒', hint: '英語中的 "ay"（如 say）' },
{ symbol: 'ㄠ', pinyin: 'ao', name: 'ㄠ (āo)', category: 'final', example: '熬', phrase: '熬夜的熬', hint: '英語中的 "ow"（如 cow）' },
{ symbol: 'ㄡ', pinyin: 'ou', name: 'ㄡ (ōu)', category: 'final', example: '歐', phrase: '歐洲的歐', hint: '英語中的 "o"（如 go）' },
{ symbol: 'ㄢ', pinyin: 'an', name: 'ㄢ (ān)', category: 'final', example: '安', phrase: '安全的安', hint: '前鼻音，英語中的 "an"（如 pan）' },
{ symbol: 'ㄣ', pinyin: 'en', name: 'ㄣ (ēn)', category: 'final', example: '恩', phrase: '恩惠的恩', hint: '前鼻音，英語中的 "un"（如 under）' },
{ symbol: 'ㄤ', pinyin: 'ang', name: 'ㄤ (āng)', category: 'final', example: '昂', phrase: '昂貴的昂', hint: '後鼻音，英語中的 "ong"（如 song）' },
{ symbol: 'ㄥ', pinyin: 'eng', name: 'ㄥ (ēng)', category: 'final', example: '風', phrase: '東風的風（韻母）', hint: '後鼻音，英語中的 "ung"（如 lung）' },
{ symbol: 'ㄦ', pinyin: 'er', name: 'ㄦ (ēr)', category: 'final', example: '兒', phrase: '兒童的兒', hint: '捲舌音，英語中的 "er"（如 her）' },
  { symbol: 'ㄚ', pinyin: 'a', name: 'ㄚ (ā)', category: 'final', example: '阿', phrase: '阿姨的阿', hint: '英語中的 "a"（如 father）' },
  { symbol: 'ㄚ', pinyin: 'a', name: 'ㄚ (ā)', category: 'final', example: '爸', phrase: '爸爸的爸（韻母）', hint: '英語中的 "a"（如 father）' },
  { symbol: 'ㄛ', pinyin: 'o', name: 'ㄛ (ō)', category: 'final', example: '波', phrase: '波浪的波（韻母）', hint: '英語中的 "aw"（如 law）' },
  { symbol: 'ㄛ', pinyin: 'o', name: 'ㄛ (ō)', category: 'final', example: '我', phrase: '我們的我（韻母）', hint: '英語中的 "aw"（如 law）' },
  { symbol: 'ㄜ', pinyin: 'e', name: 'ㄜ (ē)', category: 'final', example: '哥', phrase: '哥哥的哥（韻母）', hint: '發音介於 "uh" 與 "eh" 之間（如 up）' },
  { symbol: 'ㄜ', pinyin: 'e', name: 'ㄜ (ē)', category: 'final', example: '車', phrase: '自行車的車（韻母）', hint: '發音介於 "uh" 與 "eh" 之間（如 up）' },
  { symbol: 'ㄝ', pinyin: 'eh', name: 'ㄝ (ê)', category: 'final', example: '葉', phrase: '樹葉的葉（韻母）', hint: '英語中的 "e"（如 yes 中的 ye）' },
  { symbol: 'ㄝ', pinyin: 'eh', name: 'ㄝ (ê)', category: 'final', example: '姊', phrase: '姊姊的姊（韻母）', hint: '英語中的 "e"（如 yes 中的 ye）' },
  { symbol: 'ㄞ', pinyin: 'ai', name: 'ㄞ (āi)', category: 'final', example: '買', phrase: '買東西的買（韻母）', hint: '英語中的 "eye"（如 fly 中的 y）' },
  { symbol: 'ㄞ', pinyin: 'ai', name: 'ㄞ (āi)', category: 'final', example: '白', phrase: '白色的白（韻母）', hint: '英語中的 "eye"（如 fly 中的 y）' },
  { symbol: 'ㄟ', pinyin: 'ei', name: 'ㄟ (ēi)', category: 'final', example: '美', phrase: '美麗的美（韻母）', hint: '英語中的 "ay"（如 say）' },
  { symbol: 'ㄟ', pinyin: 'ei', name: 'ㄟ (ēi)', category: 'final', example: '妹', phrase: '妹妹的妹（韻母）', hint: '英語中的 "ay"（如 say）' },
  { symbol: 'ㄠ', pinyin: 'ao', name: 'ㄠ (āo)', category: 'final', example: '貓', phrase: '貓咪的貓（韻母）', hint: '英語中的 "ow"（如 cow）' },
  { symbol: 'ㄠ', pinyin: 'ao', name: 'ㄠ (āo)', category: 'final', example: '跑', phrase: '跑步的跑（韻母）', hint: '英語中的 "ow"（如 cow）' },
  { symbol: 'ㄡ', pinyin: 'ou', name: 'ㄡ (ōu)', category: 'final', example: '狗', phrase: '小狗的狗（韻母）', hint: '英語中的 "o"（如 go）' },
  { symbol: 'ㄡ', pinyin: 'ou', name: 'ㄡ (ōu)', category: 'final', example: '手', phrase: '雙手的手（韻母）', hint: '英語中的 "o"（如 go）' },
  { symbol: 'ㄢ', pinyin: 'an', name: 'ㄢ (ān)', category: 'final', example: '山', phrase: '高山的山（韻母）', hint: '前鼻音，英語中的 "an"（如 pan）' },
  { symbol: 'ㄢ', pinyin: 'an', name: 'ㄢ (ān)', category: 'final', example: '藍', phrase: '藍色的藍（韻母）', hint: '前鼻音，英語中的 "an"（如 pan）' },
  { symbol: 'ㄣ', pinyin: 'en', name: 'ㄣ (ēn)', category: 'final', example: '門', phrase: '大門的門（韻母）', hint: '前鼻音，英語中的 "un"（如 under）' },
  { symbol: 'ㄣ', pinyin: 'en', name: 'ㄣ (ēn)', category: 'final', example: '針', phrase: '指南針的針（韻母）', hint: '前鼻音，英語中的 "un"（如 under）' },
  { symbol: 'ㄤ', pinyin: 'ang', name: 'ㄤ (āng)', category: 'final', example: '胖', phrase: '肥胖的胖（韻母）', hint: '後鼻音，英語中的 "ong"（如 song）' },
  { symbol: 'ㄤ', pinyin: 'ang', name: 'ㄤ (āng)', category: 'final', example: '糖', phrase: '糖果的糖（韻母）', hint: '後鼻音，英語中的 "ong"（如 song）' },
  { symbol: 'ㄥ', pinyin: 'eng', name: 'ㄥ (ēng)', category: 'final', example: '冷', phrase: '冷氣的冷（韻母）', hint: '後鼻音，英語中的 "ung"（如 lung）' },
  { symbol: 'ㄥ', pinyin: 'eng', name: 'ㄥ (ēng)', category: 'final', example: '能', phrase: '能力的能（韻母）', hint: '後鼻音，英語中的 "ung"（如 lung）' },
  { symbol: 'ㄦ', pinyin: 'er', name: 'ㄦ (ēr)', category: 'final', example: '耳', phrase: '耳朵的耳（韻母）', hint: '捲舌音，英語中的 "er"（如 her）' },
  { symbol: 'ㄦ', pinyin: 'er', name: 'ㄦ (ēr)', category: 'final', example: '二', phrase: '數字二的二', hint: '捲舌音，英語中的 "er"（如 her）' },

  // --- 合成音/結合韻 Syllable Synthesis ---
{ symbol: 'ㄧㄚ', pinyin: 'ya', name: 'ㄧㄚ (ya)', category: 'synthesis', example: '鴨', phrase: '鴨子的鴨', hint: '類似英語中的 "ya"（如 yard）', audioText: '壓' },
{ symbol: 'ㄧㄛ', pinyin: 'yo', name: 'ㄧㄛ (yo)', category: 'synthesis', example: '唷', phrase: '哎唷的唷', hint: '類似英語中的 "yo"（如 yo-yo）', audioText: '唷' },
{ symbol: 'ㄧㄝ', pinyin: 'ye', name: 'ㄧㄝ (ye)', category: 'synthesis', example: '椰', phrase: '椰子的椰', hint: '類似英語中的 "ye"（如 yes）', audioText: '椰' },
{ symbol: 'ㄧㄠ', pinyin: 'yao', name: 'ㄧㄠ (yao)', category: 'synthesis', example: '妖', phrase: '妖怪的妖', hint: '類似英語中的 "yow"（如 yowl）', audioText: '腰' },
{ symbol: 'ㄧㄡ', pinyin: 'you', name: 'ㄧㄡ (you)', category: 'synthesis', example: '優', phrase: '優秀的優', hint: '類似英語中的 "yo"（如 yoke）', audioText: '優' },
{ symbol: 'ㄧㄢ', pinyin: 'yan', name: 'ㄧㄢ (yan)', category: 'synthesis', example: '煙', phrase: '抽煙的煙', hint: '類似英語中的 "yen"（如 yen）', audioText: '菸' },
{ symbol: 'ㄧㄣ', pinyin: 'yin', name: 'ㄧㄣ (yin)', category: 'synthesis', example: '音', phrase: '音樂的音', hint: '類似英語中的 "in"（如 bin）', audioText: '因' },
{ symbol: 'ㄧㄤ', pinyin: 'yang', name: 'ㄧㄤ (yang)', category: 'synthesis', example: '羊', phrase: '山羊的羊', hint: '類似英語中的 "young"（如 young）', audioText: '央' },
{ symbol: 'ㄧㄥ', pinyin: 'ying', name: 'ㄧㄥ (ying)', category: 'synthesis', example: '櫻', phrase: '櫻花的櫻', hint: '類似英語中的 "ing"（如 sing）', audioText: '英' },
{ symbol: 'ㄨㄚ', pinyin: 'wa', name: 'ㄨㄚ (wa)', category: 'synthesis', example: '蛙', phrase: '青蛙的蛙', hint: '類似英語中的 "wa"（如 water）', audioText: '蛙' },
{ symbol: 'ㄨㄛ', pinyin: 'wo', name: 'ㄨㄛ (wo)', category: 'synthesis', example: '窩', phrase: '鳥窩的窩', hint: '類似英語中的 "wo"（如 woke）', audioText: '窩' },
{ symbol: 'ㄨㄞ', pinyin: 'wai', name: 'ㄨㄞ (wai)', category: 'synthesis', example: '歪', phrase: '歪斜的歪', hint: '類似英語中的 "why"（如 why）', audioText: '歪' },
{ symbol: 'ㄨㄟ', pinyin: 'wei', name: 'ㄨㄟ (wei)', category: 'synthesis', example: '威', phrase: '威風的威', hint: '類似英語中的 "way"（如 way）', audioText: '微' },
{ symbol: 'ㄨㄢ', pinyin: 'wan', name: 'ㄨㄢ (wan)', category: 'synthesis', example: '彎', phrase: '彎曲的彎', hint: '類似英語中的 "one"（如 one）', audioText: '彎' },
{ symbol: 'ㄨㄣ', pinyin: 'wen', name: 'ㄨㄣ (wen)', category: 'synthesis', example: '溫', phrase: '溫暖的溫', hint: '類似英語中的 "win"（如 win）', audioText: '溫' },
{ symbol: 'ㄨㄤ', pinyin: 'wang', name: 'ㄨㄤ (wang)', category: 'synthesis', example: '汪', phrase: '汪汪叫的汪', hint: '類似英語中的 "wong"（如 wong）', audioText: '汪' },
{ symbol: 'ㄨㄥ', pinyin: 'weng', name: 'ㄨㄥ (weng)', category: 'synthesis', example: '翁', phrase: '不倒翁的翁', hint: '類似英語中的 "wung"（如 lung）', audioText: '翁' },
{ symbol: 'ㄩㄝ', pinyin: 'yue', name: 'ㄩㄝ (yue)', category: 'synthesis', example: '月', phrase: '月亮的月', hint: '發音為 yu-eh', audioText: '約' },
{ symbol: 'ㄩㄢ', pinyin: 'yuan', name: 'ㄩㄢ (yuan)', category: 'synthesis', example: '鴛', phrase: '鴛鴦的鴛', hint: '發音為 yu-an', audioText: '冤' },
{ symbol: 'ㄩㄣ', pinyin: 'yun', name: 'ㄩㄣ (yun)', category: 'synthesis', example: '雲', phrase: '白雲的雲', hint: '發音為 yoon', audioText: '暈' },
{ symbol: 'ㄩㄥ', pinyin: 'yong', name: 'ㄩㄥ (yong)', category: 'synthesis', example: '擁', phrase: '擁抱的擁', hint: '發音為 yung', audioText: '擁' },
{ symbol: 'ㄅㄚ', pinyin: 'ba', name: 'ㄅㄚ (ba)', category: 'synthesis', example: '爸', phrase: '爸爸的爸', hint: '發音為 b-a', audioText: '八' },
{ symbol: 'ㄆㄛ', pinyin: 'po', name: 'ㄆㄛ (po)', category: 'synthesis', example: '婆', phrase: '外婆的婆', hint: '發音為 p-o', audioText: '坡' },
{ symbol: 'ㄇㄧ', pinyin: 'mi', name: 'ㄇㄧ (mi)', category: 'synthesis', example: '咪', phrase: '貓咪的咪', hint: '發音為 m-i', audioText: '咪' },
{ symbol: 'ㄈㄨ', pinyin: 'fu', name: 'ㄈㄨ (fu)', category: 'synthesis', example: '扶', phrase: '攙扶的扶', hint: '發音為 f-u', audioText: '膚' },
{ symbol: 'ㄈㄟ', pinyin: 'fei', name: 'ㄈㄟ (fei)', category: 'synthesis', example: '飛', phrase: '飛機的飛', hint: '發音為 f-ei', audioText: '飛' },
{ symbol: 'ㄉㄚ', pinyin: 'da', name: 'ㄉㄚ (da)', category: 'synthesis', example: '打', phrase: '打球的打', hint: '發音為 d-a', audioText: '搭' },
{ symbol: 'ㄊㄨ', pinyin: 'tu', name: 'ㄊㄨ (tu)', category: 'synthesis', example: '兔', phrase: '兔子的兔', hint: '發音為 t-u', audioText: '禿' },
{ symbol: 'ㄋㄧ', pinyin: 'ni', name: 'ㄋㄧ (ni)', category: 'synthesis', example: '泥', phrase: '水泥的泥', hint: '發音為 n-i', audioText: '妮' },
{ symbol: 'ㄌㄨ', pinyin: 'lu', name: 'ㄌㄨ (lu)', category: 'synthesis', example: '鹿', phrase: '長頸鹿的鹿', hint: '發音為 l-u', audioText: '嚕' },
{ symbol: 'ㄍㄨ', pinyin: 'gu', name: 'ㄍㄨ (gu)', category: 'synthesis', example: '姑', phrase: '姑姑的姑', hint: '發音為 g-u', audioText: '估' },
{ symbol: 'ㄎㄨ', pinyin: 'ku', name: 'ㄎㄨ (ku)', category: 'synthesis', example: '哭', phrase: '哭泣的哭', hint: '發音為 k-u', audioText: '哭' },
{ symbol: 'ㄏㄨ', pinyin: 'hu', name: 'ㄏㄨ (hu)', category: 'synthesis', example: '虎', phrase: '老虎的虎', hint: '發音為 h-u', audioText: '呼' },
{ symbol: 'ㄐㄧ', pinyin: 'ji', name: 'ㄐㄧ (ji)', category: 'synthesis', example: '雞', phrase: '小雞的雞', hint: '發音為 j-i', audioText: '雞' },
{ symbol: 'ㄑㄧ', pinyin: 'qi', name: 'ㄑㄧ (qi)', category: 'synthesis', example: '汽', phrase: '汽車的汽', hint: '發音為 q-i', audioText: '七' },
{ symbol: 'ㄒㄧ', pinyin: 'xi', name: 'ㄒㄧ (xi)', category: 'synthesis', example: '西', phrase: '西瓜的西', hint: '發音為 x-i', audioText: '西' },
{ symbol: 'ㄓㄨ', pinyin: 'zhu', name: 'ㄓㄨ (zhu)', category: 'synthesis', example: '豬', phrase: '小豬的豬', hint: '發音為 zh-u', audioText: '朱' },
{ symbol: 'ㄔㄨ', pinyin: 'chu', name: 'ㄔㄨ (chu)', category: 'synthesis', example: '出', phrase: '出發的出', hint: '發音為 ch-u', audioText: '出' },
{ symbol: 'ㄕㄨ', pinyin: 'shu', name: 'ㄕㄨ (shu)', category: 'synthesis', example: '書', phrase: '看書的書', hint: '發音為 sh-u', audioText: '書' },
{ symbol: 'ㄖㄨ', pinyin: 'ru', name: 'ㄖㄨ (ru)', category: 'synthesis', example: '乳', phrase: '乳牛的乳', hint: '發音為 r-u', audioText: '如' },
{ symbol: 'ㄗㄨ', pinyin: 'zu', name: 'ㄗㄨ (zu)', category: 'synthesis', example: '租', phrase: '出租的租', hint: '發音為 z-u', audioText: '租' },
{ symbol: 'ㄘㄨ', pinyin: 'cu', name: 'ㄘㄨ (cu)', category: 'synthesis', example: '粗', phrase: '粗細的粗', hint: '發音為 c-u', audioText: '粗' },
{ symbol: 'ㄙㄨ', pinyin: 'su', name: 'ㄙㄨ (su)', category: 'synthesis', example: '蘇', phrase: '蘇打的蘇', hint: '發音為 s-u', audioText: '蘇' },
  { symbol: 'ㄇㄚ', pinyin: 'mā', name: 'ㄇㄚ (mā)', category: 'synthesis', example: '媽', phrase: '媽媽的媽', hint: '發音為 m-a', audioText: '媽' },
  { symbol: 'ㄈㄚ', pinyin: 'fā', name: 'ㄈㄚ (fā)', category: 'synthesis', example: '發', phrase: '發現的發', hint: '發音為 f-a', audioText: '發' },
  { symbol: 'ㄉㄧ', pinyin: 'dī', name: 'ㄉㄧ (dī)', category: 'synthesis', example: '低', phrase: '高低的低', hint: '發音為 d-i', audioText: '低' },
  { symbol: 'ㄉㄨ', pinyin: 'dū', name: 'ㄉㄨ (dū)', category: 'synthesis', example: '都', phrase: '都市的都', hint: '發音為 d-u', audioText: '都' },
  { symbol: 'ㄊㄚ', pinyin: 'tā', name: 'ㄊㄚ (tā)', category: 'synthesis', example: '他', phrase: '他人的他', hint: '發音為 t-a', audioText: '他' },
  { symbol: 'ㄋㄨ', pinyin: 'nǔ', name: 'ㄋㄨ (nǔ)', category: 'synthesis', example: '努', phrase: '努力的努', hint: '發音為 n-u', audioText: '努' },
  { symbol: 'ㄌㄚ', pinyin: 'lā', name: 'ㄌㄚ (lā)', category: 'synthesis', example: '拉', phrase: '拉門的拉', hint: '發音為 l-a', audioText: '拉' },
  { symbol: 'ㄍㄚ', pinyin: 'gā', name: 'ㄍㄚ (gā)', category: 'synthesis', example: '咖', phrase: '咖哩的咖', hint: '發音為 g-a', audioText: '咖' },
  { symbol: 'ㄎㄚ', pinyin: 'kā', name: 'ㄎㄚ (kā)', category: 'synthesis', example: '卡', phrase: '卡片的卡', hint: '發音為 k-a', audioText: '卡' },
  { symbol: 'ㄏㄚ', pinyin: 'hā', name: 'ㄏㄚ (hā)', category: 'synthesis', example: '哈', phrase: '哈哈的哈', hint: '發音為 h-a', audioText: '哈' },
  { symbol: 'ㄐㄩ', pinyin: 'jū', name: 'ㄐㄩ (jū)', category: 'synthesis', example: '居', phrase: '居住的居', hint: '發音為 j-yu', audioText: '居' },
  { symbol: 'ㄑㄩ', pinyin: 'qū', name: 'ㄑㄩ (qū)', category: 'synthesis', example: '區', phrase: '地區的區', hint: '發音為 q-yu', audioText: '區' },
  { symbol: 'ㄒㄩ', pinyin: 'xū', name: 'ㄒㄩ (xū)', category: 'synthesis', example: '需', phrase: '需要的需', hint: '發音為 x-yu', audioText: '需' },
  { symbol: 'ㄓㄚ', pinyin: 'zhā', name: 'ㄓㄚ (zhā)', category: 'synthesis', example: '渣', phrase: '渣滓的渣', hint: '發音為 zh-a', audioText: '渣' },
  { symbol: 'ㄔㄚ', pinyin: 'chā', name: 'ㄔㄚ (chā)', category: 'synthesis', example: '叉', phrase: '交叉的叉', hint: '發音為 ch-a', audioText: '叉' },
  { symbol: 'ㄕㄚ', pinyin: 'shā', name: 'ㄕㄚ (shā)', category: 'synthesis', example: '沙', phrase: '沙子的沙', hint: '發音為 sh-a', audioText: '沙' },
  { symbol: 'ㄖㄠ', pinyin: 'rào', name: 'ㄖㄠ (rào)', category: 'synthesis', example: '繞', phrase: '繞道的繞', hint: '發音為 r-ao', audioText: '繞' },
  { symbol: 'ㄗㄚ', pinyin: 'zā', name: 'ㄗㄚ (zā)', category: 'synthesis', example: '紮', phrase: '包紮的紮', hint: '發音為 z-a', audioText: '紮' },
  { symbol: 'ㄘㄚ', pinyin: 'cā', name: 'ㄘㄚ (cā)', category: 'synthesis', example: '擦', phrase: '擦布的擦', hint: '發音為 c-a', audioText: '擦' },
  { symbol: 'ㄙㄚ', pinyin: 'sā', name: 'ㄙㄚ (sā)', category: 'synthesis', example: '撒', phrase: '撒嬌的撒', hint: '發音為 s-a', audioText: '撒' },
  { symbol: 'ㄅㄞ', pinyin: 'bāi', name: 'ㄅㄞ (bāi)', category: 'synthesis', example: '掰', phrase: '掰掰的掰', hint: '發音為 b-ai', audioText: '掰' },
  { symbol: 'ㄆㄞ', pinyin: 'pāi', name: 'ㄆㄞ (pāi)', category: 'synthesis', example: '拍', phrase: '拍手的拍', hint: '發音為 p-ai', audioText: '拍' },
  { symbol: 'ㄇㄞ', pinyin: 'māi', name: 'ㄇㄞ (māi)', category: 'synthesis', example: '麥', phrase: '麥克風的麥', hint: '發音為 m-ai', audioText: '麥' },
  { symbol: 'ㄉㄞ', pinyin: 'dāi', name: 'ㄉㄞ (dāi)', category: 'synthesis', example: '呆', phrase: '發呆的呆', hint: '發音為 d-ai', audioText: '呆' },
  { symbol: 'ㄊㄞ', pinyin: 'tāi', name: 'ㄊㄞ (tāi)', category: 'synthesis', example: '胎', phrase: '輪胎的胎', hint: '發音為 t-ai', audioText: '胎' },
  { symbol: 'ㄋㄞ', pinyin: 'nāi', name: 'ㄋㄞ (nāi)', category: 'synthesis', example: '奶', phrase: '牛奶的奶', hint: '發音為 n-ai', audioText: '奶' },
  { symbol: 'ㄌㄞ', pinyin: 'lái', name: 'ㄌㄞ (lái)', category: 'synthesis', example: '來', phrase: '來去的來', hint: '發音為 l-ai', audioText: '來' },
  { symbol: 'ㄍㄞ', pinyin: 'gāi', name: 'ㄍㄞ (gāi)', category: 'synthesis', example: '該', phrase: '應該的該', hint: '發音為 g-ai', audioText: '該' },
  { symbol: 'ㄎㄞ', pinyin: 'kāi', name: 'ㄎㄞ (kāi)', category: 'synthesis', example: '開', phrase: '開門的開', hint: '發音為 k-ai', audioText: '開' },
  { symbol: 'ㄏㄞ', pinyin: 'hāi', name: 'ㄏㄞ (hāi)', category: 'synthesis', example: '嗨', phrase: '嗨唷的嗨', hint: '發音為 h-ai', audioText: '嗨' },
  { symbol: 'ㄓㄞ', pinyin: 'zhāi', name: 'ㄓㄞ (zhāi)', category: 'synthesis', example: '摘', phrase: '摘花的摘', hint: '發音為 zh-ai', audioText: '摘' },
  { symbol: 'ㄔㄞ', pinyin: 'chāi', name: 'ㄔㄞ (chāi)', category: 'synthesis', example: '拆', phrase: '拆開的拆', hint: '發音為 ch-ai', audioText: '拆' },
  { symbol: 'ㄕㄞ', pinyin: 'shāi', name: 'ㄕㄞ (shāi)', category: 'synthesis', example: '篩', phrase: '篩選的篩', hint: '發音為 sh-ai', audioText: '篩' },
  { symbol: 'ㄗㄞ', pinyin: 'zāi', name: 'ㄗㄞ (zāi)', category: 'synthesis', example: '災', phrase: '災難的災', hint: '發音為 z-ai', audioText: '災' },
  { symbol: 'ㄘㄞ', pinyin: 'cāi', name: 'ㄘㄞ (cāi)', category: 'synthesis', example: '猜', phrase: '猜猜的猜', hint: '發音為 c-ai', audioText: '猜' },
  { symbol: 'ㄙㄞ', pinyin: 'sāi', name: 'ㄙㄞ (sāi)', category: 'synthesis', example: '塞', phrase: '塞車的塞', hint: '發音為 s-ai', audioText: '塞' },
  { symbol: 'ㄅㄧ', pinyin: 'bī', name: 'ㄅㄧ (bī)', category: 'synthesis', example: '逼', phrase: '逼迫的逼', hint: '發音為 b-i', audioText: '逼' },
  { symbol: 'ㄆㄧ', pinyin: 'pī', name: 'ㄆㄧ (pī)', category: 'synthesis', example: '批', phrase: '批改的批', hint: '發音為 p-i', audioText: '批' },
  { symbol: 'ㄋㄧ', pinyin: 'nī', name: 'ㄋㄧ (nī)', category: 'synthesis', example: '妮', phrase: '小妮的妮', hint: '發音為 n-i', audioText: '妮' },
  { symbol: 'ㄌㄧ', pinyin: 'lī', name: 'ㄌㄧ (lī)', category: 'synthesis', example: '哩', phrase: '英哩的哩', hint: '發音為 l-i', audioText: '哩' },
  { symbol: 'ㄍㄨㄛ', pinyin: 'guō', name: 'ㄍㄨㄛ (guō)', category: 'synthesis', example: '鍋', phrase: '火鍋的鍋', hint: '發音為 g-wo', audioText: '鍋' },
  { symbol: 'ㄎㄨㄛ', pinyin: 'kuò', name: 'ㄎㄨㄛ (kuò)', category: 'synthesis', example: '闊', phrase: '遼闊的闊', hint: '發音為 k-wo', audioText: '闊' },
  { symbol: 'ㄏㄨㄛ', pinyin: 'huō', name: 'ㄏㄨㄛ (huō)', category: 'synthesis', example: '豁', phrase: '豁然的豁', hint: '發音為 h-wo', audioText: '豁' },
  { symbol: 'ㄓㄨㄛ', pinyin: 'zhuō', name: 'ㄓㄨㄛ (zhuō)', category: 'synthesis', example: '桌', phrase: '桌子的桌', hint: '發音為 zh-wo', audioText: '桌' },
  { symbol: 'ㄔㄨㄛ', pinyin: 'chuō', name: 'ㄔㄨㄛ (chuō)', category: 'synthesis', example: '戳', phrase: '郵戳的戳', hint: '發音為 ch-wo', audioText: '戳' },
  { symbol: 'ㄕㄨㄛ', pinyin: 'shuō', name: 'ㄕㄨㄛ (shuō)', category: 'synthesis', example: '說', phrase: '說話的說', hint: '發音為 sh-wo', audioText: '說' },
  { symbol: 'ㄖㄨㄛ', pinyin: 'ruò', name: 'ㄖㄨㄛˋ (ruò)', category: 'synthesis', example: '若', phrase: '假若的若', hint: '發音為 r-wo', audioText: '若' },
  { symbol: 'ㄗㄨㄛ', pinyin: 'zuō', name: 'ㄗㄨㄛ (zuō)', category: 'synthesis', example: '作', phrase: '作坊的作', hint: '發音為 z-wo', audioText: '作' },
  { symbol: 'ㄘㄨㄛ', pinyin: 'cuō', name: 'ㄘㄨㄛ (cuō)', category: 'synthesis', example: '搓', phrase: '搓手的搓', hint: '發音為 c-wo', audioText: '搓' },
  { symbol: 'ㄙㄨㄛ', pinyin: 'suō', name: 'ㄙㄨㄛ (suō)', category: 'synthesis', example: '縮', phrase: '縮小的縮', hint: '發音為 s-wo', audioText: '縮' },
  { symbol: 'ㄐㄧㄚ', pinyin: 'jiā', name: 'ㄐㄧㄚ (jiā)', category: 'synthesis', example: '家', phrase: '家庭的家', hint: '發音為 j-i-a', audioText: '家' },
  { symbol: 'ㄑㄧㄚ', pinyin: 'qiā', name: 'ㄑㄧㄚ (qiā)', category: 'synthesis', example: '掐', phrase: '掐住的掐', hint: '發音為 q-i-a', audioText: '掐' },
  { symbol: 'ㄒㄧㄚ', pinyin: 'xiā', name: 'ㄒㄧㄚ (xiā)', category: 'synthesis', example: '蝦', phrase: '小蝦的蝦', hint: '發音為 x-i-a', audioText: '蝦' },
  { symbol: 'ㄍㄨㄚ', pinyin: 'guā', name: 'ㄍㄨㄚ (guā)', category: 'synthesis', example: '瓜', phrase: '西瓜的瓜', hint: '發音為 g-u-a', audioText: '瓜' },
  { symbol: 'ㄎㄨㄚ', pinyin: 'kuā', name: 'ㄎㄨㄚ (kuā)', category: 'synthesis', example: '誇', phrase: '誇獎的誇', hint: '發音為 k-u-a', audioText: '誇' },
  { symbol: 'ㄏㄨㄚ', pinyin: 'huā', name: 'ㄏㄨㄚ (huā)', category: 'synthesis', example: '花', phrase: '花朵的花', hint: '發音為 h-u-a', audioText: '花' },
  { symbol: 'ㄓㄨㄚ', pinyin: 'zhuā', name: 'ㄓㄨㄚ (zhuā)', category: 'synthesis', example: '抓', phrase: '抓取的抓', hint: '發音為 zh-u-a', audioText: '抓' },
  { symbol: 'ㄕㄨㄚ', pinyin: 'shuā', name: 'ㄕㄨㄚ (shuā)', category: 'synthesis', example: '刷', phrase: '牙刷的刷', hint: '發音為 sh-u-a', audioText: '刷' },
  { symbol: 'ㄐㄧㄝ', pinyin: 'jiē', name: 'ㄐㄧㄝ (jiē)', category: 'synthesis', example: '街', phrase: '街道的街', hint: '發音為 j-i-e', audioText: '街' },
  { symbol: 'ㄑㄧㄝ', pinyin: 'qiē', name: 'ㄑㄧㄝ (qiē)', category: 'synthesis', example: '切', phrase: '切菜的切', hint: '發音為 q-i-e', audioText: '切' },

  // --- 聲調挑戰 Tone Challenge ---
{ symbol: 'ㄅㄚ', pinyin: 'bā', name: 'ㄅㄚ (bā)', category: 'tone', baseSyllable: 'ㄅㄚ', example: '八', phrase: '數字八的八 (一聲)', hint: '一聲 (Flat)', audioText: '八' },
{ symbol: 'ㄅㄚˊ', pinyin: 'bá', name: 'ㄅㄚˊ (bá)', category: 'tone', baseSyllable: 'ㄅㄚ', example: '拔', phrase: '拔河的拔 (二聲)', hint: '二聲 (Rising)', audioText: '拔' },
{ symbol: 'ㄅㄚˇ', pinyin: 'bǎ', name: 'ㄅㄚˇ (bǎ)', category: 'tone', baseSyllable: 'ㄅㄚ', example: '靶', phrase: '打靶的靶 (三聲)', hint: '三聲 (Dipping)', audioText: '靶' },
{ symbol: 'ㄅㄚˋ', pinyin: 'bà', name: 'ㄅㄚˋ (bà)', category: 'tone', baseSyllable: 'ㄅㄚ', example: '爸', phrase: '爸爸的爸 (四聲)', hint: '四聲 (Falling)', audioText: '爸' },
{ symbol: '˙ㄅㄚ', pinyin: 'ba', name: '˙ㄅㄚ (ba)', category: 'tone', baseSyllable: 'ㄅㄚ', example: '吧', phrase: '走吧的吧 (輕聲)', hint: '輕聲 (Neutral)', audioText: '吧' },
{ symbol: 'ㄆㄛ', pinyin: 'pō', name: 'ㄆㄛ (pō)', category: 'tone', baseSyllable: 'ㄆㄛ', example: '坡', phrase: '山坡的坡 (一聲)', hint: '一聲 (Flat)', audioText: '坡' },
{ symbol: 'ㄆㄛˊ', pinyin: 'pó', name: 'ㄆㄛˊ (pó)', category: 'tone', baseSyllable: 'ㄆㄛ', example: '婆', phrase: '老婆的婆 (二聲)', hint: '二聲 (Rising)', audioText: '婆' },
{ symbol: 'ㄆㄛˇ', pinyin: 'pǒ', name: 'ㄆㄛˇ (pǒ)', category: 'tone', baseSyllable: 'ㄆㄛ', example: '頗', phrase: '偏頗的頗 (三聲)', hint: '三聲 (Dipping)', audioText: '頗' },
{ symbol: 'ㄆㄛˋ', pinyin: 'pò', name: 'ㄆㄛˋ (pò)', category: 'tone', baseSyllable: 'ㄆㄛ', example: '破', phrase: '破爛的破 (四聲)', hint: '四聲 (Falling)', audioText: '破' },
{ symbol: 'ㄇㄧ', pinyin: 'mī', name: 'ㄇㄧ (mī)', category: 'tone', baseSyllable: 'ㄇㄧ', example: '咪', phrase: '貓咪的咪 (一聲)', hint: '一聲 (Flat)', audioText: '咪' },
{ symbol: 'ㄇㄧˊ', pinyin: 'mí', name: 'ㄇㄧˊ (mí)', category: 'tone', baseSyllable: 'ㄇㄧ', example: '迷', phrase: '迷路的迷 (二聲)', hint: '二聲 (Rising)', audioText: '迷' },
{ symbol: 'ㄇㄧˇ', pinyin: 'mǐ', name: 'ㄇㄧˇ (mǐ)', category: 'tone', baseSyllable: 'ㄇㄧ', example: '米', phrase: '白米的米 (三聲)', hint: '三聲 (Dipping)', audioText: '米' },
{ symbol: 'ㄇㄧˋ', pinyin: 'mì', name: 'ㄇㄧˋ (mì)', category: 'tone', baseSyllable: 'ㄇㄧ', example: '密', phrase: '秘密的密 (四聲)', hint: '四聲 (Falling)', audioText: '密' },
{ symbol: 'ㄈㄨ', pinyin: 'fū', name: 'ㄈㄨ (fū)', category: 'tone', baseSyllable: 'ㄈㄨ', example: '膚', phrase: '皮膚的膚 (一聲)', hint: '一聲 (Flat)', audioText: '膚' },
{ symbol: 'ㄈㄨˊ', pinyin: 'fú', name: 'ㄈㄨˊ (fú)', category: 'tone', baseSyllable: 'ㄈㄨ', example: '福', phrase: '福氣的福 (二聲)', hint: '二聲 (Rising)', audioText: '福' },
{ symbol: 'ㄈㄨˇ', pinyin: 'fǔ', name: 'ㄈㄨˇ (fǔ)', category: 'tone', baseSyllable: 'ㄈㄨ', example: '府', phrase: '政府的府 (三聲)', hint: '三聲 (Dipping)', audioText: '府' },
{ symbol: 'ㄈㄨˋ', pinyin: 'fù', name: 'ㄈㄨˋ (fù)', category: 'tone', baseSyllable: 'ㄈㄨ', example: '富', phrase: '富有的富 (四聲)', hint: '四聲 (Falling)', audioText: '富' },
{ symbol: 'ㄈㄟ', pinyin: 'fēi', name: 'ㄈㄟ (fēi)', category: 'tone', baseSyllable: 'ㄈㄟ', example: '飛', phrase: '飛機的飛 (一聲)', hint: '一聲 (Flat)', audioText: '飛' },
{ symbol: 'ㄈㄟˊ', pinyin: 'féi', name: 'ㄈㄟˊ (féi)', category: 'tone', baseSyllable: 'ㄈㄟ', example: '肥', phrase: '肥胖的肥 (二聲)', hint: '二聲 (Rising)', audioText: '肥' },
{ symbol: 'ㄈㄟˇ', pinyin: 'fěi', name: 'ㄈㄟˇ (fěi)', category: 'tone', baseSyllable: 'ㄈㄟ', example: '匪', phrase: '土匪的匪 (三聲)', hint: '三聲 (Dipping)', audioText: '匪' },
{ symbol: 'ㄈㄟˋ', pinyin: 'fèi', name: 'ㄈㄟˋ (fèi)', category: 'tone', baseSyllable: 'ㄈㄟ', example: '費', phrase: '免費的費 (四聲)', hint: '四聲 (Falling)', audioText: '費' },
{ symbol: 'ㄉㄚ', pinyin: 'dā', name: 'ㄉㄚ (dā)', category: 'tone', baseSyllable: 'ㄉㄚ', example: '搭', phrase: '搭車的搭 (一聲)', hint: '一聲 (Flat)', audioText: '搭' },
{ symbol: 'ㄉㄚˊ', pinyin: 'dá', name: 'ㄉㄚˊ (dá)', category: 'tone', baseSyllable: 'ㄉㄚ', example: '答', phrase: '回答的答 (二聲)', hint: '二聲 (Rising)', audioText: '答' },
{ symbol: 'ㄉㄚˇ', pinyin: 'dǎ', name: 'ㄉㄚˇ (dǎ)', category: 'tone', baseSyllable: 'ㄉㄚ', example: '打', phrase: '打球的打 (三聲)', hint: '三聲 (Dipping)', audioText: '打' },
{ symbol: 'ㄉㄚˋ', pinyin: 'dà', name: 'ㄉㄚˋ (dà)', category: 'tone', baseSyllable: 'ㄉㄚ', example: '大', phrase: '大小的大 (四聲)', hint: '四聲 (Falling)', audioText: '大' },
{ symbol: 'ㄌㄨ', pinyin: 'lū', name: 'ㄌㄨ (lū)', category: 'tone', baseSyllable: 'ㄌㄨ', example: '嚕', phrase: '呼嚕的嚕 (一聲)', hint: '一聲 (Flat)', audioText: '嚕' },
{ symbol: 'ㄌㄨˊ', pinyin: 'lú', name: 'ㄌㄨˊ (lú)', category: 'tone', baseSyllable: 'ㄌㄨ', example: '爐', phrase: '火爐的爐 (二聲)', hint: '二聲 (Rising)', audioText: '爐' },
{ symbol: 'ㄌㄨˇ', pinyin: 'lǔ', name: 'ㄌㄨˇ (lǔ)', category: 'tone', baseSyllable: 'ㄌㄨ', example: '魯', phrase: '魯肉的魯 (三聲)', hint: '三聲 (Dipping)', audioText: '魯' },
{ symbol: 'ㄌㄨˋ', pinyin: 'lù', name: 'ㄌㄨˋ (lù)', category: 'tone', baseSyllable: 'ㄌㄨ', example: '路', phrase: '道路的路 (四聲)', hint: '四聲 (Falling)', audioText: '路' },
{ symbol: 'ㄒㄧ', pinyin: 'xī', name: 'ㄒㄧ (xī)', category: 'tone', baseSyllable: 'ㄒㄧ', example: '西', phrase: '東西的西 (一聲)', hint: '一聲 (Flat)', audioText: '西' },
{ symbol: 'ㄒㄧˊ', pinyin: 'xí', name: 'ㄒㄧˊ (xí)', category: 'tone', baseSyllable: 'ㄒㄧ', example: '席', phrase: '主席的席 (二聲)', hint: '二聲 (Rising)', audioText: '席' },
{ symbol: 'ㄒㄧˇ', pinyin: 'xǐ', name: 'ㄒㄧˇ (xǐ)', category: 'tone', baseSyllable: 'ㄒㄧ', example: '洗', phrase: '洗衣服的洗 (三聲)', hint: '三聲 (Dipping)', audioText: '洗' },
{ symbol: 'ㄒㄧˋ', pinyin: 'xì', name: 'ㄒㄧˋ (xì)', category: 'tone', baseSyllable: 'ㄒㄧ', example: '細', phrase: '粗細的細 (四聲)', hint: '四聲 (Falling)', audioText: '細' },
  { symbol: 'ㄇㄚ', pinyin: 'mā', name: 'ㄇㄚ (mā)', category: 'tone', baseSyllable: 'ㄇㄚ', example: '媽', phrase: '媽媽的媽 (一聲)', hint: '一聲 (Flat)', audioText: '媽' },
  { symbol: 'ㄇㄚˊ', pinyin: 'má', name: 'ㄇㄚˊ (má)', category: 'tone', baseSyllable: 'ㄇㄚ', example: '麻', phrase: '芝麻的麻 (二聲)', hint: '二聲 (Rising)', audioText: '麻' },
  { symbol: 'ㄇㄚˇ', pinyin: 'mǎ', name: 'ㄇㄚˇ (mǎ)', category: 'tone', baseSyllable: 'ㄇㄚ', example: '馬', phrase: '小馬的馬 (三聲)', hint: '三聲 (Dipping)', audioText: '馬' },
  { symbol: 'ㄇㄚˋ', pinyin: 'mà', name: 'ㄇㄚˋ (mà)', category: 'tone', baseSyllable: 'ㄇㄚ', example: '罵', phrase: '責罵的罵 (四聲)', hint: '四聲 (Falling)', audioText: '罵' },
  { symbol: '˙ㄇㄚ', pinyin: 'ma', name: '˙ㄇㄚ (ma)', category: 'tone', baseSyllable: 'ㄇㄚ', example: '嗎', phrase: '好嗎的嗎 (輕聲)', hint: '輕聲 (Neutral)', audioText: '嗎' },
  { symbol: 'ㄉㄧ', pinyin: 'dī', name: 'ㄉㄧ (dī)', category: 'tone', baseSyllable: 'ㄉㄧ', example: '低', phrase: '高低的低 (一聲)', hint: '一聲 (Flat)', audioText: '低' },
  { symbol: 'ㄉㄧˊ', pinyin: 'dí', name: 'ㄉㄧˊ (dí)', category: 'tone', baseSyllable: 'ㄉㄧ', example: '笛', phrase: '笛子的笛 (二聲)', hint: '二聲 (Rising)', audioText: '笛' },
  { symbol: 'ㄉㄧˇ', pinyin: 'dǐ', name: 'ㄉㄧˇ (dǐ)', category: 'tone', baseSyllable: 'ㄉㄧ', example: '底', phrase: '海底的底 (三聲)', hint: '三聲 (Dipping)', audioText: '底' },
  { symbol: 'ㄉㄧˋ', pinyin: 'dì', name: 'ㄉㄧˋ (dì)', category: 'tone', baseSyllable: 'ㄉㄧ', example: '地', phrase: '土地的地 (四聲)', hint: '四聲 (Falling)', audioText: '地' },
  { symbol: 'ㄍㄨ', pinyin: 'gū', name: 'ㄍㄨ (gū)', category: 'tone', baseSyllable: 'ㄍㄨ', example: '估', phrase: '估計的估 (一聲)', hint: '一聲 (Flat)', audioText: '估' },
  { symbol: 'ㄍㄨˊ', pinyin: 'gú', name: 'ㄍㄨˊ (gú)', category: 'tone', baseSyllable: 'ㄍㄨ', example: '骨', phrase: '骨骼的骨 (二聲 - 特殊音)', hint: '二聲 (Rising)', audioText: '骨' },
  { symbol: 'ㄍㄨˇ', pinyin: 'gǔ', name: 'ㄍㄨˇ (gǔ)', category: 'tone', baseSyllable: 'ㄍㄨ', example: '鼓', phrase: '打鼓的鼓 (三聲)', hint: '三聲 (Dipping)', audioText: '鼓' },
  { symbol: 'ㄍㄨˋ', pinyin: 'gù', name: 'ㄍㄨˋ (gù)', category: 'tone', baseSyllable: 'ㄍㄨ', example: '故', phrase: '故事的故 (四聲)', hint: '四聲 (Falling)', audioText: '故' },
  { symbol: '˙ㄍㄨ', pinyin: 'gu', name: '˙ㄍㄨ (gu)', category: 'tone', baseSyllable: 'ㄍㄨ', example: '姑', phrase: '尼姑的姑 (輕聲)', hint: '輕聲 (Neutral)', audioText: '姑' },
  { symbol: 'ㄐㄧ', pinyin: 'jī', name: 'ㄐㄧ (jī)', category: 'tone', baseSyllable: 'ㄐㄧ', example: '雞', phrase: '小雞的雞 (一聲)', hint: '一聲 (Flat)', audioText: '雞' },
  { symbol: 'ㄐㄧˊ', pinyin: 'jí', name: 'ㄐㄧˊ (jí)', category: 'tone', baseSyllable: 'ㄐㄧ', example: '急', phrase: '著急的急 (二聲)', hint: '二聲 (Rising)', audioText: '急' },
  { symbol: 'ㄐㄧˇ', pinyin: 'jǐ', name: 'ㄐㄧˇ (jǐ)', category: 'tone', baseSyllable: 'ㄐㄧ', example: '己', phrase: '自己的己 (三聲)', hint: '三聲 (Dipping)', audioText: '己' },
  { symbol: 'ㄐㄧˋ', pinyin: 'jì', name: 'ㄐㄧˋ (jì)', category: 'tone', baseSyllable: 'ㄐㄧ', example: '記', phrase: '日記的記 (四聲)', hint: '四聲 (Falling)', audioText: '記' },
  { symbol: '˙ㄐㄧ', pinyin: 'ji', name: '˙ㄐㄧ (ji)', category: 'tone', baseSyllable: 'ㄐㄧ', example: '脊', phrase: '脊樑的脊 (輕聲)', hint: '輕聲 (Neutral)', audioText: '脊' },
  { symbol: 'ㄕㄨ', pinyin: 'shū', name: 'ㄕㄨ (shū)', category: 'tone', baseSyllable: 'ㄕㄨ', example: '書', phrase: '看書的書 (一聲)', hint: '一聲 (Flat)', audioText: '書' },
  { symbol: 'ㄕㄨˊ', pinyin: 'shú', name: 'ㄕㄨˊ (shú)', category: 'tone', baseSyllable: 'ㄕㄨ', example: '熟', phrase: '成熟的熟 (二聲)', hint: '二聲 (Rising)', audioText: '熟' },
  { symbol: 'ㄕㄨˇ', pinyin: 'shǔ', name: 'ㄕㄨˇ (shǔ)', category: 'tone', baseSyllable: 'ㄕㄨ', example: '暑', phrase: '暑假的暑 (三聲)', hint: '三聲 (Dipping)', audioText: '暑' },
  { symbol: 'ㄕㄨˋ', pinyin: 'shù', name: 'ㄕㄨˋ (shù)', category: 'tone', baseSyllable: 'ㄕㄨ', example: '樹', phrase: '大樹的樹 (四聲)', hint: '四聲 (Falling)', audioText: '樹' },
  { symbol: '˙ㄕㄨ', pinyin: 'shu', name: '˙ㄕㄨ (shu)', category: 'tone', baseSyllable: 'ㄕㄨ', example: '叔', phrase: '叔叔的叔 (輕聲)', hint: '輕聲 (Neutral)', audioText: '叔' },
  { symbol: 'ㄗㄨ', pinyin: 'zū', name: 'ㄗㄨ (zū)', category: 'tone', baseSyllable: 'ㄗㄨ', example: '租', phrase: '出租的租 (一聲)', hint: '一聲 (Flat)', audioText: '租' },
  { symbol: 'ㄗㄨˊ', pinyin: 'zú', name: 'ㄗㄨˊ (zú)', category: 'tone', baseSyllable: 'ㄗㄨ', example: '族', phrase: '家族的族 (二聲)', hint: '二聲 (Rising)', audioText: '族' },
  { symbol: 'ㄗㄨˇ', pinyin: 'zǔ', name: 'ㄗㄨˇ (zǔ)', category: 'tone', baseSyllable: 'ㄗㄨ', example: '祖', phrase: '祖先的祖 (三聲)', hint: '三聲 (Dipping)', audioText: '祖' },
  { symbol: 'ㄗㄨˋ', pinyin: 'zù', name: 'ㄗㄨˋ (zù)', category: 'tone', baseSyllable: 'ㄗㄨ', example: '詛', phrase: '詛咒的詛 (四聲)', hint: '四聲 (Falling)', audioText: '詛' },
  { symbol: 'ㄨㄚ', pinyin: 'wā', baseSyllable: 'ㄨㄚ', example: '蛙', phrase: '青蛙的蛙 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄨㄚ (wā)', audioText: '蛙' },
  { symbol: 'ㄨㄚˊ', pinyin: 'wá', baseSyllable: 'ㄨㄚ', example: '娃', phrase: '娃娃的娃 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄨㄚˊ (wá)', audioText: '娃' },
  { symbol: 'ㄨㄚˇ', pinyin: 'wǎ', baseSyllable: 'ㄨㄚ', example: '瓦', phrase: '瓦片的瓦 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄨㄚˇ (wǎ)', audioText: '瓦' },
  { symbol: 'ㄨㄚˋ', pinyin: 'wà', baseSyllable: 'ㄨㄚ', example: '襪', phrase: '襪子的襪 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄨㄚˋ (wà)', audioText: '襪' },
  { symbol: '˙ㄨㄚ', pinyin: 'wa', baseSyllable: 'ㄨㄚ', example: '哇', phrase: '好哇的哇 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄨㄚ (wa)', audioText: '哇' },
  { symbol: 'ㄧㄚ', pinyin: 'yā', baseSyllable: 'ㄧㄚ', example: '鴨', phrase: '鴨子的鴨 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄧㄚ (yā)', audioText: '鴨' },
  { symbol: 'ㄧㄚˊ', pinyin: 'yá', baseSyllable: 'ㄧㄚ', example: '牙', phrase: '牙齒的牙 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄧㄚˊ (yá)', audioText: '牙' },
  { symbol: 'ㄧㄚˇ', pinyin: 'yǎ', baseSyllable: 'ㄧㄚ', example: '雅', phrase: '優雅的雅 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄧㄚˇ (yǎ)', audioText: '雅' },
  { symbol: 'ㄧㄚˋ', pinyin: 'yà', baseSyllable: 'ㄧㄚ', example: '亞', phrase: '亞洲的亞 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄧㄚˋ (yà)', audioText: '亞' },
  { symbol: '˙ㄧㄚ', pinyin: 'ya', baseSyllable: 'ㄧㄚ', example: '呀', phrase: '對呀的呀 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄧㄚ (ya)', audioText: '呀' },
  { symbol: 'ㄍㄜ', pinyin: 'gē', baseSyllable: 'ㄍㄜ', example: '歌', phrase: '唱歌的歌 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄍㄜ (gē)', audioText: '歌' },
  { symbol: 'ㄍㄜˊ', pinyin: 'gé', baseSyllable: 'ㄍㄜ', example: '閣', phrase: '閣樓的閣 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄍㄜˊ (gé)', audioText: '閣' },
  { symbol: 'ㄍㄜˇ', pinyin: 'gě', baseSyllable: 'ㄍㄜ', example: '葛', phrase: '葛藤的葛 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄍㄜˇ (gě)', audioText: '葛' },
  { symbol: 'ㄍㄜˋ', pinyin: 'gè', baseSyllable: 'ㄍㄜ', example: '個', phrase: '個人的個 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄍㄜˋ (gè)', audioText: '個' },
  { symbol: '˙ㄍㄜ', pinyin: 'ge', baseSyllable: 'ㄍㄜ', example: '哥', phrase: '哥哥的哥 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄍㄜ (ge)', audioText: '哥' },
  { symbol: 'ㄎㄜ', pinyin: 'kē', baseSyllable: 'ㄎㄜ', example: '顆', phrase: '一顆的顆 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄎㄜ (kē)', audioText: '顆' },
  { symbol: 'ㄎㄜˊ', pinyin: 'ké', baseSyllable: 'ㄎㄜ', example: '咳', phrase: '咳嗽的咳 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄎㄜˊ (ké)', audioText: '咳' },
  { symbol: 'ㄎㄜˇ', pinyin: 'kě', baseSyllable: 'ㄎㄜ', example: '渴', phrase: '口渴的渴 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄎㄜˇ (kě)', audioText: '渴' },
  { symbol: 'ㄎㄜˋ', pinyin: 'kè', baseSyllable: 'ㄎㄜ', example: '課', phrase: '課本的課 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄎㄜˋ (kè)', audioText: '課' },
  { symbol: 'ㄌㄧ', pinyin: 'lī', baseSyllable: 'ㄌㄧ', example: '哩', phrase: '英哩的哩 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄌㄧ (lī)', audioText: '哩' },
  { symbol: 'ㄌㄧˊ', pinyin: 'lí', baseSyllable: 'ㄌㄧ', example: '梨', phrase: '梨子的梨 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄌㄧˊ (lí)', audioText: '梨' },
  { symbol: 'ㄌㄧˇ', pinyin: 'lǐ', baseSyllable: 'ㄌㄧ', example: '禮', phrase: '禮物的禮 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄌㄧˇ (lǐ)', audioText: '禮' },
  { symbol: 'ㄌㄧˋ', pinyin: 'lì', baseSyllable: 'ㄌㄧ', example: '麗', phrase: '美麗的麗 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄌㄧˋ (lì)', audioText: '麗' },
  { symbol: '˙ㄌㄧ', pinyin: 'li', baseSyllable: 'ㄌㄧ', example: '哩', phrase: '口頭的哩 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄌㄧ (li)', audioText: '哩' },
  { symbol: 'ㄒㄧㄤ', pinyin: 'xiāng', baseSyllable: 'ㄒㄧㄤ', example: '香', phrase: '香蕉的香 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄒㄧㄤ (xiāng)', audioText: '香' },
  { symbol: 'ㄒㄧㄤˊ', pinyin: 'xiáng', baseSyllable: 'ㄒㄧㄤ', example: '祥', phrase: '吉祥的祥 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄒㄧㄤˊ (xiáng)', audioText: '祥' },
  { symbol: 'ㄒㄧㄤˇ', pinyin: 'xiǎng', baseSyllable: 'ㄒㄧㄤ', example: '想', phrase: '想法的想 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄒㄧㄤˇ (xiǎng)', audioText: '想' },
  { symbol: 'ㄒㄧㄤˋ', pinyin: 'xiàng', baseSyllable: 'ㄒㄧㄤ', example: '向', phrase: '方向的向 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄒㄧㄤˋ (xiàng)', audioText: '向' },
  { symbol: 'ㄗㄠ', pinyin: 'zāo', baseSyllable: 'ㄗㄠ', example: '遭', phrase: '遭遇的遭 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄗㄠ (zāo)', audioText: '遭' },
  { symbol: 'ㄗㄠˊ', pinyin: 'záo', baseSyllable: 'ㄗㄠ', example: '鑿', phrase: '開鑿的鑿 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄗㄠˊ (záo)', audioText: '鑿' },
  { symbol: 'ㄗㄠˇ', pinyin: 'zǎo', baseSyllable: 'ㄗㄠ', example: '早', phrase: '早安的早 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄗㄠˇ (zǎo)', audioText: '早' },
  { symbol: 'ㄗㄠˋ', pinyin: 'zào', baseSyllable: 'ㄗㄠ', example: '造', phrase: '製造的造 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄗㄠˋ (zào)', audioText: '造' },
  { symbol: 'ㄉㄨㄛ', pinyin: 'duō', baseSyllable: 'ㄉㄨㄛ', example: '多', phrase: '許許多多的多 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄉㄨㄛ (duō)', audioText: '多' },
  { symbol: 'ㄉㄨㄛˊ', pinyin: 'duó', baseSyllable: 'ㄉㄨㄛ', example: '奪', phrase: '奪取的奪 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄉㄨㄛˊ (duó)', audioText: '奪' },
  { symbol: 'ㄉㄨㄛˇ', pinyin: 'duǒ', baseSyllable: 'ㄉㄨㄛ', example: '躲', phrase: '躲藏的躲 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄉㄨㄛˇ (duǒ)', audioText: '躲' },
  { symbol: 'ㄉㄨㄛˋ', pinyin: 'duò', baseSyllable: 'ㄉㄨㄛ', example: '剁', phrase: '剁肉的剁 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄉㄨㄛˋ (duò)', audioText: '剁' },
  { symbol: '˙ㄉㄨㄛ', pinyin: 'duo', baseSyllable: 'ㄉㄨㄛ', example: '朵', phrase: '花朵的朵 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄉㄨㄛ (duo)', audioText: '朵' },
  { symbol: 'ㄊㄨㄛ', pinyin: 'tuō', baseSyllable: 'ㄊㄨㄛ', example: '拖', phrase: '拖鞋的拖 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄊㄨㄛ (tuō)', audioText: '拖' },
  { symbol: 'ㄊㄨㄛˊ', pinyin: 'tuó', baseSyllable: 'ㄊㄨㄛ', example: '駝', phrase: '駱駝的駝 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄊㄨㄛˊ (tuó)', audioText: '駝' },
  { symbol: 'ㄊㄨㄛˇ', pinyin: 'tuǒ', baseSyllable: 'ㄊㄨㄛ', example: '妥', phrase: '妥協的妥 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄊㄨㄛˇ (tuǒ)', audioText: '妥' },
  { symbol: 'ㄊㄨㄛˋ', pinyin: 'tuò', baseSyllable: 'ㄊㄨㄛ', example: '拓', phrase: '開拓的拓 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄊㄨㄛˋ (tuò)', audioText: '拓' },
  { symbol: 'ㄌㄨㄛ', pinyin: 'luō', baseSyllable: 'ㄌㄨㄛ', example: '囉', phrase: '囉嗦的囉 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄌㄨㄛ (luō)', audioText: '囉' },
  { symbol: 'ㄌㄨㄛˊ', pinyin: 'luó', baseSyllable: 'ㄌㄨㄛ', example: '羅', phrase: '羅盤的羅 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄌㄨㄛˊ (luó)', audioText: '羅' },
  { symbol: 'ㄌㄨㄛˇ', pinyin: 'luǒ', baseSyllable: 'ㄌㄨㄛ', example: '裸', phrase: '赤裸的裸 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄌㄨㄛˇ (luǒ)', audioText: '裸' },
  { symbol: 'ㄌㄨㄛˋ', pinyin: 'luò', baseSyllable: 'ㄌㄨㄛ', example: '落', phrase: '降落的落 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄌㄨㄛˋ (luò)', audioText: '落' },
  { symbol: '˙ㄌㄨㄛ', pinyin: 'luo', baseSyllable: 'ㄌㄨㄛ', example: '囉', phrase: '好囉的囉 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄌㄨㄛ (luo)', audioText: '囉' },
  { symbol: 'ㄅㄧㄥ', pinyin: 'bīng', baseSyllable: 'ㄅㄧㄥ', example: '冰', phrase: '冰箱的冰 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄅㄧㄥ (bīng)', audioText: '冰' },
  { symbol: 'ㄅㄧㄥˊ', pinyin: 'bíng', baseSyllable: 'ㄅㄧㄥ', example: 'ㄅㄧㄥˊ', phrase: 'ㄅㄧㄥˊ (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄅㄧㄥˊ (bíng)', audioText: 'ㄅㄧㄥˊ' },
  { symbol: 'ㄅㄧㄥˇ', pinyin: 'bǐng', baseSyllable: 'ㄅㄧㄥ', example: '丙', phrase: '甲乙丙的丙 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄅㄧㄥˇ (bǐng)', audioText: '丙' },
  { symbol: 'ㄅㄧㄥˋ', pinyin: 'bìng', baseSyllable: 'ㄅㄧㄥ', example: '病', phrase: '生病的病 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄅㄧㄥˋ (bìng)', audioText: '病' },
  { symbol: 'ㄉㄧㄥ', pinyin: 'dīng', baseSyllable: 'ㄉㄧㄥ', example: '丁', phrase: '園丁的丁 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄉㄧㄥ (dīng)', audioText: '丁' },
  { symbol: 'ㄉㄧㄥˊ', pinyin: 'díng', baseSyllable: 'ㄉㄧㄥ', example: 'ㄉㄧㄥˊ', phrase: 'ㄉㄧㄥˊ (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄉㄧㄥˊ (díng)', audioText: 'ㄉㄧㄥˊ' },
  { symbol: 'ㄉㄧㄥˇ', pinyin: 'dǐng', baseSyllable: 'ㄉㄧㄥ', example: '頂', phrase: '山頂的頂 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄉㄧㄥˇ (dǐng)', audioText: '頂' },
  { symbol: 'ㄉㄧㄥˋ', pinyin: 'dìng', baseSyllable: 'ㄉㄧㄥ', example: '定', phrase: '決定的定 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄉㄧㄥˋ (dìng)', audioText: '定' },
  { symbol: 'ㄌㄧㄥ', pinyin: 'līng', baseSyllable: 'ㄌㄧㄥ', example: '拎', phrase: '提拎的拎 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄌㄧㄥ (līng)', audioText: '拎' },
  { symbol: 'ㄌㄧㄥˊ', pinyin: 'líng', baseSyllable: 'ㄌㄧㄥ', example: '鈴', phrase: '鈴聲的鈴 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄌㄧㄥˊ (líng)', audioText: '鈴' },
  { symbol: 'ㄌㄧㄥˇ', pinyin: 'lǐng', baseSyllable: 'ㄌㄧㄥ', example: '領', phrase: '帶領的領 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄌㄧㄥˇ (lǐng)', audioText: '領' },
  { symbol: 'ㄌㄧㄥˋ', pinyin: 'lìng', baseSyllable: 'ㄌㄧㄥ', example: '另', phrase: '另外的另 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄌㄧㄥˋ (lìng)', audioText: '另' },
  { symbol: 'ㄍㄨㄢ', pinyin: 'guān', baseSyllable: 'ㄍㄨㄢ', example: '關', phrase: '開關的關 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄍㄨㄢ (guān)', audioText: '關' },
  { symbol: 'ㄍㄨㄢˊ', pinyin: 'guán', baseSyllable: 'ㄍㄨㄢ', example: 'ㄍㄨㄢˊ', phrase: 'ㄍㄨㄢˊ (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄍㄨㄢˊ (guán)', audioText: 'ㄍㄨㄢˊ' },
  { symbol: 'ㄍㄨㄢˇ', pinyin: 'guǎn', baseSyllable: 'ㄍㄨㄢ', example: '管', phrase: '水管的管 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄍㄨㄢˇ (guǎn)', audioText: '管' },
  { symbol: 'ㄍㄨㄢˋ', pinyin: 'guàn', baseSyllable: 'ㄍㄨㄢ', example: '灌', phrase: '灌溉的灌 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄍㄨㄢˋ (guàn)', audioText: '灌' },
  { symbol: 'ㄅㄢ', pinyin: 'bān', baseSyllable: 'ㄅㄢ', example: '班', phrase: '上班的班 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄅㄢ (bān)', audioText: '班' },
  { symbol: 'ㄅㄢˊ', pinyin: 'bán', baseSyllable: 'ㄅㄢ', example: 'ㄅㄢˊ', phrase: 'ㄅㄢˊ (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄅㄢˊ (bán)', audioText: 'ㄅㄢˊ' },
  { symbol: 'ㄅㄢˇ', pinyin: 'bǎn', baseSyllable: 'ㄅㄢ', example: '板', phrase: '黑板的板 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄅㄢˇ (bǎn)', audioText: '板' },
  { symbol: 'ㄅㄢˋ', pinyin: 'bàn', baseSyllable: 'ㄅㄢ', example: '半', phrase: '一半的半 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄅㄢˋ (bàn)', audioText: '半' },
  { symbol: 'ㄆㄢ', pinyin: 'pān', baseSyllable: 'ㄆㄢ', example: '攀', phrase: '攀爬的攀 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄆㄢ (pān)', audioText: '攀' },
  { symbol: 'ㄆㄢˊ', pinyin: 'pán', baseSyllable: 'ㄆㄢ', example: '盤', phrase: '盤子的盤 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄆㄢˊ (pán)', audioText: '盤' },
  { symbol: 'ㄆㄢˇ', pinyin: 'pǎn', baseSyllable: 'ㄆㄢ', example: 'ㄆㄢˇ', phrase: 'ㄆㄢˇ (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄆㄢˇ (pǎn)', audioText: 'ㄆㄢˇ' },
  { symbol: 'ㄆㄢˋ', pinyin: 'pàn', baseSyllable: 'ㄆㄢ', example: '盼', phrase: '期盼的盼 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄆㄢˋ (pàn)', audioText: '盼' },
  { symbol: 'ㄉㄢ', pinyin: 'dān', baseSyllable: 'ㄉㄢ', example: '單', phrase: '名單的單 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄉㄢ (dān)', audioText: '單' },
  { symbol: 'ㄉㄢˊ', pinyin: 'dán', baseSyllable: 'ㄉㄢ', example: '談', phrase: '談天的談 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄉㄢˊ (dán)', audioText: '談' },
  { symbol: 'ㄉㄢˇ', pinyin: 'dǎn', baseSyllable: 'ㄉㄢ', example: '膽', phrase: '膽量的膽 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄉㄢˇ (dǎn)', audioText: '膽' },
  { symbol: 'ㄉㄢˋ', pinyin: 'dàn', baseSyllable: 'ㄉㄢ', example: '蛋', phrase: '雞蛋的蛋 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄉㄢˋ (dàn)', audioText: '蛋' },
  { symbol: 'ㄕㄢ', pinyin: 'shān', baseSyllable: 'ㄕㄢ', example: '山', phrase: '高山的山 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄕㄢ (shān)', audioText: '山' },
  { symbol: 'ㄕㄢˊ', pinyin: 'shán', baseSyllable: 'ㄕㄢ', example: 'ㄕㄢˊ', phrase: 'ㄕㄢˊ (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄕㄢˊ (shán)', audioText: 'ㄕㄢˊ' },
  { symbol: 'ㄕㄢˇ', pinyin: 'shǎn', baseSyllable: 'ㄕㄢ', example: '閃', phrase: '閃電的閃 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄕㄢˇ (shǎn)', audioText: '閃' },
  { symbol: 'ㄕㄢˋ', pinyin: 'shàn', baseSyllable: 'ㄕㄢ', example: '扇', phrase: '風扇的扇 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄕㄢˋ (shàn)', audioText: '扇' },
  { symbol: 'ㄗㄢ', pinyin: 'zān', baseSyllable: 'ㄗㄢ', example: '簪', phrase: '髮簪的簪 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄗㄢ (zān)', audioText: '簪' },
  { symbol: 'ㄗㄢˊ', pinyin: 'zán', baseSyllable: 'ㄗㄢ', example: '咱', phrase: '咱們的咱 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄗㄢˊ (zán)', audioText: '咱' },
  { symbol: 'ㄗㄢˇ', pinyin: 'zǎn', baseSyllable: 'ㄗㄢ', example: '攢', phrase: '積攢的積 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄗㄢˇ (zǎn)', audioText: '攢' },
  { symbol: 'ㄗㄢˋ', pinyin: 'zàn', baseSyllable: 'ㄗㄢ', example: '讚', phrase: '按讚的讚 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄗㄢˋ (zàn)', audioText: '讚' },
  { symbol: 'ㄍㄤ', pinyin: 'gāng', baseSyllable: 'ㄍㄤ', example: '鋼', phrase: '鋼琴的鋼 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄍㄤ (gāng)', audioText: '鋼' },
  { symbol: 'ㄍㄤˊ', pinyin: 'gáng', baseSyllable: 'ㄍㄤ', example: 'ㄍㄤˊ', phrase: 'ㄍㄤˊ (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄍㄤˊ (gáng)', audioText: 'ㄍㄤˊ' },
  { symbol: 'ㄍㄤˇ', pinyin: 'gǎng', baseSyllable: 'ㄍㄤ', example: '港', phrase: '港口的港 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄍㄤˇ (gǎng)', audioText: '港' },
  { symbol: 'ㄍㄤˋ', pinyin: 'gàng', baseSyllable: 'ㄍㄤ', example: '槓', phrase: '單槓的槓 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄍㄤˋ (gàng)', audioText: '槓' },
  { symbol: 'ㄍㄨㄛ', pinyin: 'guō', baseSyllable: 'ㄍㄨㄛ', example: '鍋', phrase: '火鍋的鍋 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄍㄨㄛ (guō)', audioText: '鍋' },
  { symbol: 'ㄍㄨㄛˊ', pinyin: 'guó', baseSyllable: 'ㄍㄨㄛ', example: '國', phrase: '國家的國 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄍㄨㄛˊ (guó)', audioText: '國' },
  { symbol: 'ㄍㄨㄛˇ', pinyin: 'guǒ', baseSyllable: 'ㄍㄨㄛ', example: '果', phrase: '水果的果 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄍㄨㄛˇ (guǒ)', audioText: '果' },
  { symbol: 'ㄍㄨㄛˋ', pinyin: 'guò', baseSyllable: 'ㄍㄨㄛ', example: '過', phrase: '過去的過 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄍㄨㄛˋ (guò)', audioText: '過' },
  { symbol: 'ㄐㄧㄚ', pinyin: 'jiā', baseSyllable: 'ㄐㄧㄚ', example: '家', phrase: '家庭的家 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄐㄧㄚ (jiā)', audioText: '家' },
  { symbol: 'ㄐㄧㄚˊ', pinyin: 'jiá', baseSyllable: 'ㄐㄧㄚ', example: '夾', phrase: '夾子的夾 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄐㄧㄚˊ (jiá)', audioText: '夾' },
  { symbol: 'ㄐㄧㄚˇ', pinyin: 'jiǎ', baseSyllable: 'ㄐㄧㄚ', example: '甲', phrase: '甲乙的甲 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄐㄧㄚˇ (jiǎ)', audioText: '甲' },
  { symbol: 'ㄐㄧㄚˋ', pinyin: 'jià', baseSyllable: 'ㄐㄧㄚ', example: '架', phrase: '書架的架 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄐㄧㄚˋ (jià)', audioText: '架' },
  { symbol: '˙ㄐㄧㄚ', pinyin: 'jia', baseSyllable: 'ㄐㄧㄚ', example: '家', phrase: '親家的家 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄐㄧㄚ (jia)', audioText: '家' },
  { symbol: 'ㄌㄨㄢ', pinyin: 'luān', baseSyllable: 'ㄌㄨㄢ', example: 'ㄌㄨㄢ', phrase: 'ㄌㄨㄢ (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄌㄨㄢ (luān)', audioText: 'ㄌㄨㄢ' },
  { symbol: 'ㄌㄨㄢˊ', pinyin: 'luán', baseSyllable: 'ㄌㄨㄢ', example: '欒', phrase: '欒樹的欒 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄌㄨㄢˊ (luán)', audioText: '欒' },
  { symbol: 'ㄌㄨㄢˇ', pinyin: 'luǎn', baseSyllable: 'ㄌㄨㄢ', example: '卵', phrase: '雞卵的卵 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄌㄨㄢˇ (luǎn)', audioText: '卵' },
  { symbol: 'ㄌㄨㄢˋ', pinyin: 'luàn', baseSyllable: 'ㄌㄨㄢ', example: '亂', phrase: '混亂的亂 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄌㄨㄢˋ (luàn)', audioText: '亂' },
  { symbol: 'ㄇㄤ', pinyin: 'māng', baseSyllable: 'ㄇㄤ', example: '牤', phrase: '牤牛的牤 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄇㄤ (māng)', audioText: '牤' },
  { symbol: 'ㄇㄤˊ', pinyin: 'máng', baseSyllable: 'ㄇㄤ', example: '忙', phrase: '幫忙的忙 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄇㄤˊ (máng)', audioText: '忙' },
  { symbol: 'ㄇㄤˇ', pinyin: 'mǎng', baseSyllable: 'ㄇㄤ', example: '莽', phrase: '魯莽的莽 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄇㄤˇ (mǎng)', audioText: '莽' },
  { symbol: 'ㄇㄤˋ', pinyin: 'màng', baseSyllable: 'ㄇㄤ', example: '漭', phrase: '漭漭的漭 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄇㄤˋ (màng)', audioText: '漭' },
  { symbol: 'ㄅㄠ', pinyin: 'bāo', baseSyllable: 'ㄅㄠ', example: '包', phrase: '包子的包 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄅㄠ (bāo)', audioText: '包' },
  { symbol: 'ㄅㄠˊ', pinyin: 'báo', baseSyllable: 'ㄅㄠ', example: '薄', phrase: '薄厚薄的薄 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄅㄠˊ (báo)', audioText: '薄' },
  { symbol: 'ㄅㄠˇ', pinyin: 'bǎo', baseSyllable: 'ㄅㄠ', example: '飽', phrase: '吃飽的飽 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄅㄠˇ (bǎo)', audioText: '飽' },
  { symbol: 'ㄅㄠˋ', pinyin: 'bào', baseSyllable: 'ㄅㄠ', example: '報', phrase: '報紙的報 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄅㄠˋ (bào)', audioText: '報' },
  { symbol: '˙ㄅㄠ', pinyin: 'bao', baseSyllable: 'ㄅㄠ', example: '胞', phrase: '同胞的胞 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄅㄠ (bao)', audioText: '胞' },
  { symbol: 'ㄆㄠ', pinyin: 'pāo', baseSyllable: 'ㄆㄠ', example: '拋', phrase: '拋球的拋 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄆㄠ (pāo)', audioText: '拋' },
  { symbol: 'ㄆㄠˊ', pinyin: 'páo', baseSyllable: 'ㄆㄠ', example: '刨', phrase: '刨冰的刨 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄆㄠˊ (páo)', audioText: '刨' },
  { symbol: 'ㄆㄠˇ', pinyin: 'pǎo', baseSyllable: 'ㄆㄠ', example: '跑', phrase: '跑步的跑 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄆㄠˇ (pǎo)', audioText: '跑' },
  { symbol: 'ㄆㄠˋ', pinyin: 'pào', baseSyllable: 'ㄆㄠ', example: '泡', phrase: '泡茶的泡 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄆㄠˋ (pào)', audioText: '泡' },
  { symbol: 'ㄇㄠ', pinyin: 'māo', baseSyllable: 'ㄇㄠ', example: '貓', phrase: '貓咪的貓 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄇㄠ (māo)', audioText: '貓' },
  { symbol: 'ㄇㄠˊ', pinyin: 'máo', baseSyllable: 'ㄇㄠ', example: '毛', phrase: '毛巾的毛 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄇㄠˊ (máo)', audioText: '毛' },
  { symbol: 'ㄇㄠˇ', pinyin: 'mǎo', baseSyllable: 'ㄇㄠ', example: '錨', phrase: '船錨的錨 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄇㄠˇ (mǎo)', audioText: '錨' },
  { symbol: 'ㄇㄠˋ', pinyin: 'mào', baseSyllable: 'ㄇㄠ', example: '帽', phrase: '帽子的帽 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄇㄠˋ (mào)', audioText: '帽' },
  { symbol: 'ㄉㄠ', pinyin: 'dāo', baseSyllable: 'ㄉㄠ', example: '刀', phrase: '小刀的刀 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄉㄠ (dāo)', audioText: '刀' },
  { symbol: 'ㄉㄠˊ', pinyin: 'dáo', baseSyllable: 'ㄉㄠ', example: '叨', phrase: '叨天叨的叨 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄉㄠˊ (dáo)', audioText: '叨' },
  { symbol: 'ㄉㄠˇ', pinyin: 'dǎo', baseSyllable: 'ㄉㄠ', example: '島', phrase: '海島的島 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄉㄠˇ (dǎo)', audioText: '島' },
  { symbol: 'ㄉㄠˋ', pinyin: 'dào', baseSyllable: 'ㄉㄠ', example: '到', phrase: '來到的到 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄉㄠˋ (dào)', audioText: '到' },
  { symbol: '˙ㄉㄠ', pinyin: 'dao', baseSyllable: 'ㄉㄠ', example: '叨', phrase: '嘮叨的叨 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄉㄠ (dao)', audioText: '叨' },
  { symbol: 'ㄊㄠ', pinyin: 'tāo', baseSyllable: 'ㄊㄠ', example: '掏', phrase: '掏錢的掏 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄊㄠ (tāo)', audioText: '掏' },
  { symbol: 'ㄊㄠˊ', pinyin: 'táo', baseSyllable: 'ㄊㄠ', example: '桃', phrase: '桃子的桃 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄊㄠˊ (táo)', audioText: '桃' },
  { symbol: 'ㄊㄠˇ', pinyin: 'tǎo', baseSyllable: 'ㄊㄠ', example: '討', phrase: '討厭的討 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄊㄠˇ (tǎo)', audioText: '討' },
  { symbol: 'ㄊㄠˋ', pinyin: 'tào', baseSyllable: 'ㄊㄠ', example: '套', phrase: '手套的套 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄊㄠˋ (tào)', audioText: '套' },
  { symbol: '˙ㄊㄠ', pinyin: 'tao', baseSyllable: 'ㄊㄠ', example: '叨', phrase: '叨光的叨 (輕聲)', hint: '輕聲 (Neutral)', category: 'tone', name: '˙ㄊㄠ (tao)', audioText: '叨' },
  { symbol: 'ㄋㄠ', pinyin: 'nāo', baseSyllable: 'ㄋㄠ', example: '孬', phrase: '孬種的孬 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄋㄠ (nāo)', audioText: '孬' },
  { symbol: 'ㄋㄠˊ', pinyin: 'náo', baseSyllable: 'ㄋㄠ', example: '撓', phrase: '抓撓的撓 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄋㄠˊ (náo)', audioText: '撓' },
  { symbol: 'ㄋㄠˇ', pinyin: 'nǎo', baseSyllable: 'ㄋㄠ', example: '腦', phrase: '電腦的腦 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄋㄠˇ (nǎo)', audioText: '腦' },
  { symbol: 'ㄋㄠˋ', pinyin: 'nào', baseSyllable: 'ㄋㄠ', example: '鬧', phrase: '熱鬧的鬧 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄋㄠˋ (nào)', audioText: '鬧' },
  { symbol: 'ㄌㄠ', pinyin: 'lāo', baseSyllable: 'ㄌㄠ', example: '撈', phrase: '撈魚的撈 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄌㄠ (lāo)', audioText: '撈' },
  { symbol: 'ㄌㄠˊ', pinyin: 'láo', baseSyllable: 'ㄌㄠ', example: '牢', phrase: '牢房的牢 (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄌㄠˊ (láo)', audioText: '牢' },
  { symbol: 'ㄌㄠˇ', pinyin: 'lǎo', baseSyllable: 'ㄌㄠ', example: '老', phrase: '老師的老 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄌㄠˇ (lǎo)', audioText: '老' },
  { symbol: 'ㄌㄠˋ', pinyin: 'lào', baseSyllable: 'ㄌㄠ', example: '烙', phrase: '烙印的烙 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄌㄠˋ (lào)', audioText: '烙' },
  { symbol: 'ㄍㄠ', pinyin: 'gāo', baseSyllable: 'ㄍㄠ', example: '高', phrase: '高山的高 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄍㄠ (gāo)', audioText: '高' },
  { symbol: 'ㄍㄠˊ', pinyin: 'gáo', baseSyllable: 'ㄍㄠ', example: 'ㄍㄠˊ', phrase: 'ㄍㄠˊ (二聲)', hint: '二聲 (Rising)', category: 'tone', name: 'ㄍㄠˊ (gáo)', audioText: 'ㄍㄠˊ' },
  { symbol: 'ㄍㄠˇ', pinyin: 'gǎo', baseSyllable: 'ㄍㄠ', example: '稿', phrase: '稿紙的稿 (三聲)', hint: '三聲 (Dipping)', category: 'tone', name: 'ㄍㄠˇ (gǎo)', audioText: '稿' },
  { symbol: 'ㄍㄠˋ', pinyin: 'gào', baseSyllable: 'ㄍㄠ', example: '告', phrase: '告訴的告 (四聲)', hint: '四聲 (Falling)', category: 'tone', name: 'ㄍㄠˋ (gào)', audioText: '告' },
  { symbol: 'ㄎㄠ', pinyin: 'kāo', baseSyllable: 'ㄎㄠ', example: '尻', phrase: '尻川的尻 (一聲)', hint: '一聲 (Flat)', category: 'tone', name: 'ㄎㄠ (kāo)', audioText: '尻' },

  // --- 完整單字挑戰 Vocabulary Challenge ---
{ symbol: 'ㄓㄨㄛ ㄗ˙', pinyin: 'zhuōzi', name: 'ㄓㄨㄛ ㄗ˙ (zhuōzi)', category: 'vocabulary', example: '桌', phrase: '桌子', hint: '桌子 (Table / Desk)', audioText: '桌子' },
{ symbol: 'ㄧˇ ㄗ˙', pinyin: 'yǐzi', name: 'ㄧˇ ㄗ˙ (yǐzi)', category: 'vocabulary', example: '椅', phrase: '椅子', hint: '椅子 (Chair)', audioText: '椅子' },
{ symbol: 'ㄆㄧㄥˊ ㄍㄨㄛˇ', pinyin: 'píngguǒ', name: 'ㄆㄧㄥˊ ㄍㄨㄛˇ (píngguǒ)', category: 'vocabulary', example: '蘋', phrase: '蘋果', hint: '蘋果 (Apple)', audioText: '蘋果' },
{ symbol: 'ㄒㄧㄤ ㄐㄧㄠ', pinyin: 'xiāngjiāo', name: 'ㄒㄧㄤ ㄐㄧㄠ (xiāngjiāo)', category: 'vocabulary', example: '香', phrase: '香蕉', hint: '香蕉 (Banana)', audioText: '香蕉' },
{ symbol: 'ㄈㄟ ㄐㄧ', pinyin: 'fēijī', name: 'ㄈㄟ ㄐㄧ (fēijī)', category: 'vocabulary', example: '飛', phrase: '飛機', hint: '飛機 (Airplane)', audioText: '飛機' },
{ symbol: 'ㄑㄧˋ ㄔㄜ', pinyin: 'qìchē', name: 'ㄑㄧˋ ㄔㄜ (qìchē)', category: 'vocabulary', example: '汽', phrase: '汽車', hint: '汽車 (Car)', audioText: '汽車' },
{ symbol: 'ㄒㄧ ㄍㄨㄚ', pinyin: 'xīguā', name: 'ㄒㄧ ㄍㄨㄚ (xīguā)', category: 'vocabulary', example: '西', phrase: '西瓜', hint: '西瓜 (Watermelon)', audioText: '西瓜' },
{ symbol: 'ㄇㄠ ㄇㄧ', pinyin: 'māomī', name: 'ㄇㄠ ㄇㄧ (māomī)', category: 'vocabulary', example: '貓', phrase: '貓咪', hint: '貓咪 (Cat)', audioText: '貓咪' },
{ symbol: 'ㄒㄧㄠˇ ㄍㄡˇ', pinyin: 'xiǎogǒu', name: 'ㄒㄧㄠˇ ㄍㄡˇ (xiǎogǒu)', category: 'vocabulary', example: '狗', phrase: '小狗', hint: '小狗 (Dog)', audioText: '小狗' },
{ symbol: 'ㄧ ㄈㄨˊ', pinyin: 'yīfú', name: 'ㄧ ㄈㄨˊ (yīfú)', category: 'vocabulary', example: '衣', phrase: '衣服', hint: '衣服 (Clothes)', audioText: '衣服' },
{ symbol: 'ㄉㄧㄢˋ ㄏㄨㄚˋ', pinyin: 'diànhuà', name: 'ㄉㄧㄢˋ ㄏㄨㄚˋ (diànhuà)', category: 'vocabulary', example: '電', phrase: '電話', hint: '電話 (Telephone)', audioText: '電話' },
{ symbol: 'ㄇㄧㄢˋ ㄅㄠ', pinyin: 'miànbāo', name: 'ㄇㄧㄢˋ ㄅㄠ (miànbāo)', category: 'vocabulary', example: '麵', phrase: '麵包', hint: '麵包 (Bread)', audioText: '麵包' },
{ symbol: 'ㄋㄧㄡˊ ㄋㄞˇ', pinyin: 'niúnǎi', name: 'ㄋㄧㄡˊ ㄋㄞˇ (niúnǎi)', category: 'vocabulary', example: '牛', phrase: '牛奶', hint: '牛奶 (Milk)', audioText: '牛奶' },
{ symbol: 'ㄊㄞˋ ㄧㄤˊ', pinyin: 'tàiyáng', name: 'ㄊㄞˋ ㄧㄤˊ (tàiyáng)', category: 'vocabulary', example: '太', phrase: '太陽', hint: '太陽 (Sun)', audioText: '太陽' },
{ symbol: 'ㄩㄝˋ ㄌㄧㄤˋ', pinyin: 'yuèliàng', name: 'ㄩㄝˋ ㄌㄧㄤˋ (yuèliàng)', category: 'vocabulary', example: '月', phrase: '月亮', hint: '月亮 (Moon)', audioText: '月亮' },
{ symbol: 'ㄊㄨˋ ㄗ˙', pinyin: 'tùzi', name: 'ㄊㄨˋ ㄗ˙ (tùzi)', category: 'vocabulary', example: '兔', phrase: '兔子', hint: '兔子 (Rabbit)', audioText: '兔子' },
{ symbol: 'ㄌㄠˇ ㄕ', pinyin: 'lǎoshī', name: 'ㄌㄠˇ ㄕ (lǎoshī)', category: 'vocabulary', example: '老', phrase: '老師', hint: '老師 (Teacher)', audioText: '老師' },
{ symbol: 'ㄒㄩㄝˊ ㄕㄥ', pinyin: 'xuéshēng', name: 'ㄒㄩㄝˊ ㄕㄥ (xuéshēng)', category: 'vocabulary', example: '學', phrase: '學生', hint: '學生 (Student)', audioText: '學生' },
{ symbol: 'ㄑㄧˋ ㄑㄧㄡˊ', pinyin: 'qìqiú', name: 'ㄑㄧˋ ㄑㄧㄡˊ (qìqiú)', category: 'vocabulary', example: '氣', phrase: '氣球', hint: '氣球 (Balloon)', audioText: '氣球' },
{ symbol: 'ㄅㄧㄥˇ ㄍㄢ', pinyin: 'bǐnggān', name: 'ㄅㄧㄥˇ ㄍㄢ (bǐnggān)', category: 'vocabulary', example: '餅', phrase: '餅乾', hint: '餅乾 (Cookie)', audioText: '餅乾' },
{ symbol: 'ㄕㄨㄟˇ ㄍㄨㄛˇ', pinyin: 'shuǐguǒ', name: 'ㄕㄨㄟˇ ㄍㄨㄛˇ (shuǐguǒ)', category: 'vocabulary', example: '水', phrase: '水果', hint: '水果 (Fruit)', audioText: '水果' },
{ symbol: 'ㄉㄚˋ ㄒㄧㄤˋ', pinyin: 'dàxiàng', name: 'ㄉㄚˋ ㄒㄧㄤˋ (dàxiàng)', category: 'vocabulary', example: '象', phrase: '大象', hint: '大象 (Elephant)', audioText: '大象' },
{ symbol: 'ㄕ ㄗ˙', pinyin: 'shīzi', name: 'ㄕ ㄗ˙ (shīzi)', category: 'vocabulary', example: '獅', phrase: '獅子', hint: '獅子 (Lion)', audioText: '獅子' },
{ symbol: 'ㄌㄠˇ ㄏㄨˇ', pinyin: 'lǎohǔ', name: 'ㄌㄠˇ ㄏㄨˇ (lǎohǔ)', category: 'vocabulary', example: '虎', phrase: '老虎', hint: '老虎 (Tiger)', audioText: '老虎' },
{ symbol: 'ㄔㄤˊ ㄐㄧㄥˇ ㄌㄨˋ', pinyin: 'chángjǐnglù', name: 'ㄔㄤˊ ㄐㄧㄥˇ ㄌㄨˋ (chángjǐnglù)', category: 'vocabulary', example: '鹿', phrase: '長頸鹿', hint: '長頸鹿 (Giraffe)', audioText: '長頸鹿' },
{ symbol: 'ㄅㄢ ㄇㄚˇ', pinyin: 'bānmǎ', name: 'ㄅㄢ ㄇㄚˇ (bānmǎ)', category: 'vocabulary', example: '斑', phrase: '斑馬', hint: '斑馬 (Zebra)', audioText: '斑馬' },
{ symbol: 'ㄏㄡˊ ㄗ˙', pinyin: 'hóuzi', name: 'ㄏㄡˊ ㄗ˙ (hóuzi)', category: 'vocabulary', example: '猴', phrase: '猴子', hint: '猴子 (Monkey)', audioText: '猴子' },
{ symbol: 'ㄒㄧㄛˊ ㄇㄠ', pinyin: 'xióngmāo', name: 'ㄒㄧㄛˊ ㄇㄠ (xióngmāo)', category: 'vocabulary', example: '熊', phrase: '熊貓', hint: '熊貓 (Panda)', audioText: '熊貓' },
{ symbol: 'ㄙㄨㄥ ㄕㄨˇ', pinyin: 'sōngshǔ', name: 'ㄙㄨㄥ ㄕㄨˇ (sōngshǔ)', category: 'vocabulary', example: '松', phrase: '松鼠', hint: '松鼠 (Squirrel)', audioText: '松鼠' },
{ symbol: 'ㄏㄨˊ ㄌㄧ˙', pinyin: 'húli', name: 'ㄏㄨˊ ㄌㄧ˙ (húli)', category: 'vocabulary', example: '狐', phrase: '狐狸', hint: '狐狸 (Fox)', audioText: '狐狸' },
{ symbol: 'ㄏㄨˊ ㄉㄧㄝˊ', pinyin: 'húdié', name: 'ㄏㄨˊ ㄉㄧㄝˊ (húdié)', category: 'vocabulary', example: '蝴', phrase: '蝴蝶', hint: '蝴蝶 (Butterfly)', audioText: '蝴蝶' },
{ symbol: 'ㄇㄧˋ ㄈㄥ', pinyin: 'mìfēng', name: 'ㄇㄧˋ ㄈㄥ (mìfēng)', category: 'vocabulary', example: '蜜', phrase: '蜜蜂', hint: '蜜蜂 (Honeybee)', audioText: '蜜蜂' },
{ symbol: 'ㄇㄚˇ ㄧˇ', pinyin: 'mǎyǐ', name: 'ㄇㄚˇ ㄧˇ (mǎyǐ)', category: 'vocabulary', example: '螞', phrase: '螞蟻', hint: '螞蟻 (Ant)', audioText: '螞蟻' },
{ symbol: 'ㄆㄥˊ ㄒㄧㄝˋ', pinyin: 'pángxiè', name: 'ㄆㄥˊ ㄒㄧㄝˋ (pángxiè)', category: 'vocabulary', example: '蟹', phrase: '螃蟹', hint: '螃蟹 (Crab)', audioText: '螃蟹' },
{ symbol: 'ㄑㄧㄥ ㄨㄚ', pinyin: 'qīngwā', name: 'ㄑㄧㄥ ㄨㄚ (qīngwā)', category: 'vocabulary', example: '蛙', phrase: '青蛙', hint: '青蛙 (Frog)', audioText: '青蛙' },
{ symbol: 'ㄒㄧㄠˇ ㄩˊ', pinyin: 'xiǎoyú', name: 'ㄒㄧㄠˇ ㄩˊ (xiǎoyú)', category: 'vocabulary', example: '魚', phrase: '小魚', hint: '小魚 (Fish)', audioText: '小魚' },
{ symbol: 'ㄒㄧㄠˇ ㄋㄧㄠˇ', pinyin: 'xiǎoniǎo', name: 'ㄒㄧㄠˇ ㄋㄧㄠˇ (xiǎoniǎo)', category: 'vocabulary', example: '鳥', phrase: '小鳥', hint: '小鳥 (Bird)', audioText: '小鳥' },
{ symbol: 'ㄧㄚ ㄗ˙', pinyin: 'yāzi', name: 'ㄧㄚ ㄗ˙ (yāzi)', category: 'vocabulary', example: '鴨', phrase: '鴨子', hint: '鴨子 (Duck)', audioText: '鴨子' },
{ symbol: 'ㄐㄧ ㄉㄢˋ', pinyin: 'jīdàn', name: 'ㄐㄧ ㄉㄢˋ (jīdàn)', category: 'vocabulary', example: '蛋', phrase: '雞蛋', hint: '雞蛋 (Egg)', audioText: '雞蛋' },
{ symbol: 'ㄨㄟˇ ㄅㄚ', pinyin: 'wěiba', name: 'ㄨㄟˇ ㄅㄚ (wěiba)', category: 'vocabulary', example: '尾', phrase: '尾巴', hint: '尾巴 (Tail)', audioText: '尾巴' },
{ symbol: 'ㄨㄛ ㄋㄧㄡˊ', pinyin: 'wōniú', name: 'ㄨㄛ ㄋㄧㄡˊ (wōniú)', category: 'vocabulary', example: '蝸', phrase: '蝸牛', hint: '蝸牛 (Snail)', audioText: '蝸牛' },
{ symbol: 'ㄑㄧ ㄜˊ', pinyin: 'qǐé', name: 'ㄑㄧ ㄜˊ (qǐé)', category: 'vocabulary', example: '企', phrase: '企鵝', hint: '企鵝 (Penguin)', audioText: '企鵝' },
{ symbol: 'ㄒㄩㄝˊ ㄒㄧㄠˋ', pinyin: 'xuéxiào', name: 'ㄒㄩㄝˊ ㄒㄧㄠˋ (xuéxiào)', category: 'vocabulary', example: '學', phrase: '學校', hint: '學校 (School)', audioText: '學校' },
{ symbol: 'ㄐㄧㄠˋ ㄕˋ', pinyin: 'jiàoshì', name: 'ㄐㄧㄠˋ ㄕˋ (jiàoshì)', category: 'vocabulary', example: '教', phrase: '教室', hint: '教室 (Classroom)', audioText: '教室' },
{ symbol: 'ㄕㄨ ㄅㄠ', pinyin: 'shūbāo', name: 'ㄕㄨ ㄅㄠ (shūbāo)', category: 'vocabulary', example: '書', phrase: '書包', hint: '書包 (Schoolbag)', audioText: '書包' },
{ symbol: 'ㄑㄧㄢ ㄅㄧˇ', pinyin: 'qiānbǐ', name: 'ㄑㄧㄢ ㄅㄧˇ (qiānbǐ)', category: 'vocabulary', example: '鉛', phrase: '鉛筆', hint: '鉛筆 (Pencil)', audioText: '鉛筆' },
{ symbol: 'ㄒㄧㄤˋ ㄆㄧˊ ㄘㄚ', pinyin: 'xiàngpícā', name: 'ㄒㄧㄤˋ ㄆㄧˊ ㄘㄚ (xiàngpícā)', category: 'vocabulary', example: '橡', phrase: '橡皮擦', hint: '橡皮擦 (Eraser)', audioText: '橡皮擦' },
{ symbol: 'ㄔˇ ㄗ˙', pinyin: 'chǐzi', name: 'ㄔˇ ㄗ˙ (chǐzi)', category: 'vocabulary', example: '尺', phrase: '尺子', hint: '尺子 (Ruler)', audioText: '尺子' },
{ symbol: 'ㄎㄜˋ ㄅㄣˇ', pinyin: 'kèběn', name: 'ㄎㄜˋ ㄅㄣˇ (kèběn)', category: 'vocabulary', example: '課', phrase: '課本', hint: '課本 (Textbook)', audioText: '課本' },
{ symbol: 'ㄅㄧˇ ㄐㄧˋ ㄅㄣˇ', pinyin: 'bǐjìběn', name: 'ㄅㄧˇ ㄐㄧˋ ㄅㄣˇ (bǐjìběn)', category: 'vocabulary', example: '筆', phrase: '筆記本', hint: '筆記本 (Notebook)', audioText: '筆記本' },
{ symbol: 'ㄌㄚˋ ㄅㄧˇ', pinyin: 'làbǐ', name: 'ㄌㄚˋ ㄅㄧˇ (làbǐ)', category: 'vocabulary', example: '蠟', phrase: '蠟筆', hint: '蠟筆 (Crayon)', audioText: '蠟筆' },
{ symbol: 'ㄐㄧㄢˇ ㄉㄠ', pinyin: 'jiǎndāo', name: 'ㄐㄧㄢˇ ㄉㄠ (jiǎndāo)', category: 'vocabulary', example: '剪', phrase: '剪刀', hint: '剪刀 (Scissors)', audioText: '剪刀' },
{ symbol: 'ㄐㄧㄠ ㄕㄨㄟˇ', pinyin: 'jiāoshuǐ', name: 'ㄐㄧㄠ ㄕㄨㄟˇ (jiāoshuǐ)', category: 'vocabulary', example: '膠', phrase: '膠水', hint: '膠水 (Glue)', audioText: '膠水' },
{ symbol: 'ㄐㄧㄠˇ ㄉㄧㄝˊ', pinyin: 'jiǎodíe', name: 'ㄐㄧㄠˇ ㄉㄧㄝˊ (jiǎodíe)', category: 'vocabulary', example: '角', phrase: '三角板', hint: '三角板 (Set square)', audioText: '三角板' },
{ symbol: 'ㄅㄚˋ ㄅㄚ˙', pinyin: 'bàba', name: 'ㄅㄚˋ ㄅㄚ˙ (bàba)', category: 'vocabulary', example: '爸', phrase: '爸爸', hint: '爸爸 (Father / Dad)', audioText: '爸爸' },
{ symbol: 'ㄇㄚ ㄇㄚ˙', pinyin: 'māma', name: 'ㄇㄚ ㄇㄚ˙ (māma)', category: 'vocabulary', example: '媽', phrase: '媽媽', hint: '媽媽 (Mother / Mom)', audioText: '媽媽' },
{ symbol: 'ㄍㄜ ㄍㄜ˙', pinyin: 'gēge', name: 'ㄍㄜ ㄍㄜ˙ (gēge)', category: 'vocabulary', example: '哥', phrase: '哥哥', hint: '哥哥 (Older brother)', audioText: '哥哥' },
{ symbol: 'ㄐㄧㄝˇ ㄐㄧㄝ˙', pinyin: 'jiějie', name: 'ㄐㄧㄝˇ ㄐㄧㄝ˙ (jiějie)', category: 'vocabulary', example: '姊', phrase: '姊姊', hint: '姊姊 (Older sister)', audioText: '姊姊' },
{ symbol: 'ㄉㄧˋ ㄉㄧ˙', pinyin: 'dìdi', name: 'ㄉㄧˋ ㄉㄧ˙ (dìdi)', category: 'vocabulary', example: '弟', phrase: '弟弟', hint: '弟弟 (Younger brother)', audioText: '弟弟' },
{ symbol: 'ㄇㄟˋ ㄇㄟ˙', pinyin: 'mèimei', name: 'ㄇㄟˋ ㄇㄟ˙ (mèimei)', category: 'vocabulary', example: '妹', phrase: '妹妹', hint: '妹妹 (Younger sister)', audioText: '妹妹' },
{ symbol: 'ㄧㄝˊ ㄧㄝ˙', pinyin: 'yéye', name: 'ㄧㄝˊ ㄧㄝ˙ (yéye)', category: 'vocabulary', example: '爺', phrase: '爺爺', hint: '爺爺 (Grandfather - paternal)', audioText: '爺爺' },
{ symbol: 'ㄋㄞˇ ㄋㄞ˙', pinyin: 'nǎinai', name: 'ㄋㄞˇ ㄋㄞ˙ (nǎinai)', category: 'vocabulary', example: '奶', phrase: '奶奶', hint: '奶奶 (Grandmother - paternal)', audioText: '奶奶' },
{ symbol: 'ㄧ ㄕㄥ', pinyin: 'yīshēng', name: 'ㄧ ㄕㄥ (yīshēng)', category: 'vocabulary', example: '醫', phrase: '醫生', hint: '醫生 (Doctor)', audioText: '醫生' },
{ symbol: 'ㄏㄨˋ ㄕˋ', pinyin: 'hùshì', name: 'ㄏㄨˋ ㄕˋ (hùshì)', category: 'vocabulary', example: '護', phrase: '護士', hint: '護士 (Nurse)', audioText: '護士' },
{ symbol: 'ㄐㄧㄥˇ ㄔㄚˊ', pinyin: 'jǐngchá', name: 'ㄐㄧㄥˇ ㄔㄚˊ (jǐngchá)', category: 'vocabulary', example: '警', phrase: '警察', hint: '警察 (Police)', audioText: '警察' },
{ symbol: 'ㄙ ㄐㄧ', pinyin: 'sījī', name: 'ㄙ ㄐㄧ (sījī)', category: 'vocabulary', example: '司', phrase: '司機', hint: '司機 (Driver)', audioText: '司機' },
{ symbol: 'ㄆㄥˊ ㄧㄡˇ', pinyin: 'péngyǒu', name: 'ㄆㄥˊ ㄧㄡˇ (péngyǒu)', category: 'vocabulary', example: '朋', phrase: '朋友', hint: '朋友 (Friend)', audioText: '朋友' },
{ symbol: 'ㄘㄠˇ ㄇㄟˊ', pinyin: 'cǎoméi', name: 'ㄘㄠˇ ㄇㄟˊ (cǎoméi)', category: 'vocabulary', example: '草', phrase: '草莓', hint: '草莓 (Strawberry)', audioText: '草莓' },
{ symbol: 'ㄆㄨˊ ㄊㄠˊ', pinyin: 'pútáo', name: 'ㄆㄨˊ ㄊㄠˊ (pútáo)', category: 'vocabulary', example: '葡', phrase: '葡萄', hint: '葡萄 (Grape)', audioText: '葡萄' },
{ symbol: 'ㄌㄧㄡˇ ㄉㄧㄥ', pinyin: 'liǔdīng', name: 'ㄌㄧㄡˇ ㄉㄧㄥ (liǔdīng)', category: 'vocabulary', example: '柳', phrase: '柳丁', hint: '柳丁 (Orange)', audioText: '柳丁' },
{ symbol: 'ㄇㄤˊ ㄍㄨㄛˇ', pinyin: 'mángguǒ', name: 'ㄇㄤˊ ㄍㄨㄛˇ (mángguǒ)', category: 'vocabulary', example: '芒', phrase: '芒果', hint: '芒果 (Mango)', audioText: '芒果' },
{ symbol: 'ㄧㄥ ㄊㄠˊ', pinyin: 'yīngtáo', name: 'ㄧㄥ ㄊㄠˊ (yīngtáo)', category: 'vocabulary', example: '櫻', phrase: '櫻桃', hint: '櫻桃 (Cherry)', audioText: '櫻桃' },
{ symbol: 'ㄇㄨˋ ㄍㄨㄚ', pinyin: 'mùguā', name: 'ㄇㄨˋ ㄍㄨㄚ (mùguā)', category: 'vocabulary', example: '木', phrase: '木瓜', hint: '木瓜 (Papaya)', audioText: '木瓜' },
{ symbol: 'ㄋㄧㄥˊ ㄇㄥˊ', pinyin: 'níngméng', name: 'ㄋㄧㄥˊ ㄇㄥˊ (níngméng)', category: 'vocabulary', example: '檸', phrase: '檸檬', hint: '檸檬 (Lemon)', audioText: '檸檬' },
{ symbol: 'ㄕㄨ ㄘㄞˋ', pinyin: 'shūcài', name: 'ㄕㄨ ㄘㄞˋ (shūcài)', category: 'vocabulary', example: '蔬', phrase: '蔬菜', hint: '蔬菜 (Vegetable)', audioText: '蔬菜' },
{ symbol: 'ㄇㄧˇ ㄈㄢˋ', pinyin: 'mǐfàn', name: 'ㄇㄧˇ ㄈㄢˋ (mǐfàn)', category: 'vocabulary', example: '米', phrase: '米飯', hint: '米飯 (Rice)', audioText: '米飯' },
{ symbol: 'ㄇㄧㄢˋ ㄊㄧㄠˊ', pinyin: 'miàntáo', name: 'ㄇㄧㄢˋ ㄊㄧㄠˊ (miàntáo)', category: 'vocabulary', example: '麵', phrase: '麵條', hint: '麵條 (Noodles)', audioText: '麵條' },
{ symbol: 'ㄉㄢˋ ㄍㄠ', pinyin: 'dàngāo', name: 'ㄉㄢˋ ㄍㄠ (dàngāo)', category: 'vocabulary', example: '蛋', phrase: '蛋糕', hint: '蛋糕 (Cake)', audioText: '蛋糕' },
{ symbol: 'ㄑㄧㄠˇ ㄎㄜˋ ㄌㄧˋ', pinyin: 'qiǎokèlì', name: 'ㄑㄧㄠˇ ㄎㄜˋ ㄌㄧˋ (qiǎokèlì)', category: 'vocabulary', example: '巧', phrase: '巧克力', hint: '巧克力 (Chocolate)', audioText: '巧克力' },
{ symbol: 'ㄅㄧㄥ ㄑㄧˊ ㄌㄧㄣˊ', pinyin: 'bīngqílín', name: 'ㄅㄧㄥ ㄑㄧˊ ㄌㄧㄣˊ (bīngqílín)', category: 'vocabulary', example: '冰', phrase: '冰淇淋', hint: '冰淇淋 (Ice cream)', audioText: '冰淇淋' },
{ symbol: 'ㄍㄨㄛˇ ㄓ', pinyin: 'guǒzhī', name: 'ㄍㄨㄛˇ ㄓ (guǒzhī)', category: 'vocabulary', example: '果', phrase: '果汁', hint: '果汁 (Juice)', audioText: '果汁' },
{ symbol: 'ㄔㄚˊ ㄕㄨㄟˇ', pinyin: 'cháshuǐ', name: 'ㄔㄚˊ ㄕㄨㄟˇ (cháshuǐ)', category: 'vocabulary', example: '茶', phrase: '茶水', hint: '茶水 (Tea)', audioText: '茶水' },
{ symbol: 'ㄎㄚ ㄈㄟ', pinyin: 'kāfēi', name: 'ㄎㄚ ㄈㄟ (kāfēi)', category: 'vocabulary', example: '咖', phrase: '咖啡', hint: '咖啡 (Coffee)', audioText: '咖啡' },
{ symbol: 'ㄏㄢˋ ㄅㄠˇ', pinyin: 'hànbǎo', name: 'ㄏㄢˋ ㄅㄠˇ (hànbǎo)', category: 'vocabulary', example: '漢', phrase: '漢堡', hint: '漢堡 (Hamburger)', audioText: '漢堡' },
{ symbol: 'ㄆㄧ ㄙㄚˋ', pinyin: 'pīsà', name: 'ㄆㄧ ㄙㄚˋ (pīsà)', category: 'vocabulary', example: '披', phrase: '披薩', hint: '披薩 (Pizza)', audioText: '披薩' },
{ symbol: 'ㄖㄜˋ ㄍㄡˇ', pinyin: 'règǒu', name: 'ㄖㄜˋ ㄍㄡˇ (règǒu)', category: 'vocabulary', example: '熱', phrase: '熱狗', hint: '熱狗 (Hot dog)', audioText: '熱狗' },
{ symbol: 'ㄕㄨㄟˇ ㄐㄧㄠˇ', pinyin: 'shuǐjiǎo', name: 'ㄕㄨㄟˇ ㄐㄧㄠˇ (shuǐjiǎo)', category: 'vocabulary', example: '水', phrase: '水餃', hint: '水餃 (Dumpling)', audioText: '水餃' },
{ symbol: 'ㄅㄠ ㄗ˙', pinyin: 'bāozi', name: 'ㄅㄠ ㄗ˙ (bāozi)', category: 'vocabulary', example: '包', phrase: '包子', hint: '包子 (Steamed bun)', audioText: '包子' },
{ symbol: 'ㄇㄢˊ ㄊㄡˊ', pinyin: 'mántou', name: 'ㄇㄢˊ ㄊㄡˊ (mántou)', category: 'vocabulary', example: '饅', phrase: '饅頭', hint: '饅頭 (Steamed bread)', audioText: '饅頭' },
{ symbol: 'ㄏㄨㄥˊ ㄉㄡˋ', pinyin: 'hóngdòu', name: 'ㄏㄨㄥˊ ㄉㄡˋ (hóngdòu)', category: 'vocabulary', example: '紅', phrase: '紅豆', hint: '紅豆 (Red bean)', audioText: '紅豆' },
{ symbol: 'ㄌㄩˋ ㄉㄡˋ', pinyin: 'lǜdòu', name: 'ㄌㄩˋ ㄉㄡˋ (lǜdòu)', category: 'vocabulary', example: '綠', phrase: '綠豆', hint: '綠豆 (Mung bean)', audioText: '綠豆' },
{ symbol: 'ㄏㄨㄛˇ ㄔㄜ', pinyin: 'huǒchē', name: 'ㄏㄨㄛˇ ㄔㄜ (huǒchē)', category: 'vocabulary', example: '火', phrase: '火車', hint: '火車 (Train)', audioText: '火車' },
{ symbol: 'ㄍㄠ ㄊㄧㄝˇ', pinyin: 'gāotiě', name: 'ㄍㄠ ㄊㄧㄝˇ (gāotiě)', category: 'vocabulary', example: '鐵', phrase: '高鐵', hint: '高鐵 (HSR / High Speed Rail)', audioText: '高鐵' },
{ symbol: 'ㄐㄧㄝˊ ㄩㄣˋ', pinyin: 'jiéyùn', name: 'ㄐㄧㄝˊ ㄩㄣˋ (jiéyùn)', category: 'vocabulary', example: '捷', phrase: '捷運', hint: '捷運 (MRT / Subway)', audioText: '捷運' },
{ symbol: 'ㄍㄨㄥ ㄔㄜ', pinyin: 'gōngchē', name: 'ㄍㄨㄥ ㄔㄜ (gōngchē)', category: 'vocabulary', example: '公', phrase: '公車', hint: '公車 (Bus)', audioText: '公車' },
{ symbol: 'ㄗˋ ㄒㄧㄥˊ ㄔㄜ', pinyin: 'zìxíngchē', name: 'ㄗˋ ㄒㄧㄥˊ ㄔㄜ (zìxíngchē)', category: 'vocabulary', example: '車', phrase: '自行車', hint: '自行車 (Bicycle)', audioText: '自行車' },
{ symbol: 'ㄐㄧ ㄔㄜ', pinyin: 'jīchē', name: 'ㄐㄧ ㄔㄜ (jīchē)', category: 'vocabulary', example: '機', phrase: '機車', hint: '機車 (Scooter / Motorcycle)', audioText: '機車' },
{ symbol: 'ㄔㄨㄢˊ ㄓ', pinyin: 'chuánzhī', name: 'ㄔㄨㄢˊ ㄓ (chuánzhī)', category: 'vocabulary', example: '船', phrase: '船隻', hint: '船隻 (Boat / Ship)', audioText: '船隻' },
{ symbol: 'ㄓˊ ㄕㄥ ㄐㄧ', pinyin: 'zhíshēngjī', name: 'ㄓˊ ㄕㄥ ㄐㄧ (zhíshēngjī)', category: 'vocabulary', example: '直', phrase: '直升機', hint: '直升機 (Helicopter)', audioText: '直升機' },
{ symbol: 'ㄎㄚˇ ㄔㄜ', pinyin: 'kǎchē', name: 'ㄎㄚˇ ㄔㄜ (kǎchē)', category: 'vocabulary', example: '卡', phrase: '卡車', hint: '卡車 (Truck)', audioText: '卡車' },
{ symbol: 'ㄐㄧㄥˇ ㄔㄜ', pinyin: 'jǐngchē', name: 'ㄐㄧㄥˇ ㄔㄜ (jǐngchē)', category: 'vocabulary', example: '警', phrase: '警車', hint: '警車 (Police Car)', audioText: '警車' },
{ symbol: 'ㄐㄧㄡˋ ㄏㄨˋ ㄔㄜ', pinyin: 'jiùhùchē', name: 'ㄐㄧㄡˋ ㄏㄨˋ ㄔㄜ (jiùhùchē)', category: 'vocabulary', example: '救', phrase: '救護車', hint: '救護車 (Ambulance)', audioText: '救護車' },
{ symbol: 'ㄉㄧㄢˋ ㄋㄠˇ', pinyin: 'diànnǎo', name: 'ㄉㄧㄢˋ ㄋㄠˇ (diànnǎo)', category: 'vocabulary', example: '電', phrase: '電腦', hint: '電腦 (Computer)', audioText: '電腦' },
{ symbol: 'ㄉㄧㄢˋ ㄕˋ', pinyin: 'diànshì', name: 'ㄉㄧㄢˋ ㄕˋ (diànshì)', category: 'vocabulary', example: '視', phrase: '電視', hint: '電視 (Television)', audioText: '電視' },
{ symbol: 'ㄅㄧㄥ ㄒㄧㄤ', pinyin: 'bīngxiāng', name: 'ㄅㄧㄥ ㄒㄧㄤ (bīngxiāng)', category: 'vocabulary', example: '冰', phrase: '冰箱', hint: '冰箱 (Refrigerator)', audioText: '冰箱' },
{ symbol: 'ㄒㄧˇ ㄧ ㄐㄧ', pinyin: 'xǐyījī', name: 'ㄒㄧˇ ㄧ ㄐㄧ (xǐyījī)', category: 'vocabulary', example: '洗', phrase: '洗衣機', hint: '洗衣機 (Washing Machine)', audioText: '洗衣機' },
{ symbol: 'ㄌㄥˇ ㄑㄧˋ', pinyin: 'lěngqì', name: 'ㄌㄥˇ ㄑㄧˋ (lěngqì)', category: 'vocabulary', example: '冷', phrase: '冷氣', hint: '冷氣 (Air conditioner)', audioText: '冷氣' },
{ symbol: 'ㄈㄥ ㄕㄢˋ', pinyin: 'fēngshàn', name: 'ㄈㄥ ㄕㄢˋ (fēngshàn)', category: 'vocabulary', example: '風', phrase: '風扇', hint: '風扇 (Electric Fan)', audioText: '風扇' },
{ symbol: 'ㄕㄡˇ ㄐㄧ', pinyin: 'shǒujī', name: 'ㄕㄡˇ ㄐㄧ (shǒujī)', category: 'vocabulary', example: '手', phrase: '手機', hint: '手機 (Mobile phone)', audioText: '手機' },
{ symbol: 'ㄧㄠˋ ㄕ˙', pinyin: 'yàoshi', name: 'ㄧㄠˋ ㄕ˙ (yàoshi)', category: 'vocabulary', example: '鑰', phrase: '鑰匙', hint: '鑰匙 (Key)', audioText: '鑰匙' },
{ symbol: 'ㄑㄧㄢˊ ㄅㄠ', pinyin: 'qiánbāo', name: 'ㄑㄧㄢˊ ㄅㄠ (qiánbāo)', category: 'vocabulary', example: '錢', phrase: '錢包', hint: '錢包 (Wallet)', audioText: '錢包' },
{ symbol: 'ㄕㄡˇ ㄅㄧㄠˇ', pinyin: 'shǒubiǎo', name: 'ㄕㄡˇ ㄅㄧㄠˇ (shǒubiǎo)', category: 'vocabulary', example: '錶', phrase: '手錶', hint: '手錶 (Watch)', audioText: '手錶' },
{ symbol: 'ㄧㄢˇ ㄐㄧㄥˋ', pinyin: 'yǎnjìng', name: 'ㄧㄢˇ ㄐㄧㄥˋ (yǎnjìng)', category: 'vocabulary', example: '鏡', phrase: '眼鏡', hint: '眼鏡 (Glasses)', audioText: '眼鏡' },
{ symbol: 'ㄩˇ ㄙㄢˇ', pinyin: 'yǔsǎn', name: 'ㄩˇ ㄙㄢˇ (yǔsǎn)', category: 'vocabulary', example: '傘', phrase: '雨傘', hint: '雨傘 (Umbrella)', audioText: '雨傘' },
{ symbol: 'ㄅㄟ ㄗ˙', pinyin: 'bēizi', name: 'ㄅㄟ ㄗ˙ (bēizi)', category: 'vocabulary', example: '杯', phrase: '杯子', hint: '杯子 (Cup / Glass)', audioText: '杯子' },
{ symbol: 'ㄆㄢˊ ㄗ˙', pinyin: 'pánzi', name: 'ㄆㄢˊ ㄗ˙ (pánzi)', category: 'vocabulary', example: '盤', phrase: '盤子', hint: '盤子 (Plate / Dish)', audioText: '盤子' },
{ symbol: 'ㄎㄨㄞˋ ㄗ˙', pinyin: 'kuàizi', name: 'ㄎㄨㄞˋ ㄗ˙ (kuàizi)', category: 'vocabulary', example: '筷', phrase: '筷子', hint: '筷子 (Chopsticks)', audioText: '筷子' },
{ symbol: 'ㄊㄤ ㄔˊ', pinyin: 'tāngchí', name: 'ㄊㄤ ㄔˊ (tāngchí)', category: 'vocabulary', example: '匙', phrase: '湯匙', hint: '湯匙 (Spoon)', audioText: '湯匙' },
{ symbol: 'ㄧㄚˊ ㄕㄨㄚ', pinyin: 'yáshuā', name: 'ㄧㄚˊ ㄕㄨㄚ (yáshuā)', category: 'vocabulary', example: '刷', phrase: '牙刷', hint: '牙刷 (Toothbrush)', audioText: '牙刷' },
{ symbol: 'ㄇㄠˊ ㄐㄧㄣ', pinyin: 'máojīn', name: 'ㄇㄠˊ ㄐㄧㄣ (máojīn)', category: 'vocabulary', example: '巾', phrase: '毛巾', hint: '毛巾 (Towel)', audioText: '毛巾' },
{ symbol: 'ㄈㄟˊ ㄗㄠˋ', pinyin: 'féizào', name: 'ㄈㄟˊ ㄗㄠˋ (féizào)', category: 'vocabulary', example: '皂', phrase: '肥皂', hint: '肥皂 (Soap)', audioText: '肥皂' },
{ symbol: 'ㄐㄧㄥˋ ㄗ˙', pinyin: 'jìngzi', name: 'ㄐㄧㄥˋ ㄗ˙ (jìngzi)', category: 'vocabulary', example: '鏡', phrase: '鏡子', hint: '鏡子 (Mirror)', audioText: '鏡子' },
{ symbol: 'ㄧㄚˊ ㄍㄠ', pinyin: 'yágāo', name: 'ㄧㄚˊ ㄍㄠ (yágāo)', category: 'vocabulary', example: '牙', phrase: '牙膏', hint: '牙膏 (Toothpaste)', audioText: '牙膏' },
{ symbol: 'ㄌㄜˋ ㄙㄜˋ ㄊㄨㄥˇ', pinyin: 'lèsètǒng', name: 'ㄌㄜˋ ㄙㄜˋ ㄊㄨㄥˇ (lèsètǒng)', category: 'vocabulary', example: '垃', phrase: '垃圾桶', hint: '垃圾桶 (Trash Can)', audioText: '垃圾桶' },
{ symbol: 'ㄕㄡ ㄉㄧㄢˋ ㄊㄨㄥˇ', pinyin: 'shǒudiàntǒng', name: 'ㄕㄡ ㄉㄧㄢˋ ㄊㄨㄥˇ (shǒudiàntǒng)', category: 'vocabulary', example: '電', phrase: '手電筒', hint: '手電筒 (Flashlight)', audioText: '手電筒' },
{ symbol: 'ㄒㄧㄥ ㄒㄧㄥ˙', pinyin: 'xīngxing', name: 'ㄒㄧㄥ ㄒㄧㄥ˙ (xīngxing)', category: 'vocabulary', example: '星', phrase: '星星', hint: '星星 (Star)', audioText: '星星' },
{ symbol: 'ㄅㄞˊ ㄩㄣˊ', pinyin: 'báiyún', name: 'ㄅㄞˊ ㄩㄣˊ (báiyún)', category: 'vocabulary', example: '雲', phrase: '白雲', hint: '白雲 (White Cloud)', audioText: '白雲' },
{ symbol: 'ㄒㄧㄚˋ ㄩˇ', pinyin: 'xiàyǔ', name: 'ㄒㄧㄚˋ ㄩˇ (xiàyǔ)', category: 'vocabulary', example: '雨', phrase: '下雨', hint: '下雨 (Rain)', audioText: '下雨' },
{ symbol: 'ㄍㄨㄚ ㄈㄥ', pinyin: 'guāfēng', name: 'ㄍㄨㄚ ㄈㄥ (guāfēng)', category: 'vocabulary', example: '風', phrase: '颳風', hint: '颳風 (Windy)', audioText: '颳風' },
{ symbol: 'ㄉㄚˇ ㄌㄟˊ', pinyin: 'dǎléi', name: 'ㄉㄚˇ ㄌㄟˊ (dǎléi)', category: 'vocabulary', example: '雷', phrase: '打雷', hint: '打雷 (Thunder)', audioText: '打雷' },
{ symbol: 'ㄕㄢˇ ㄉㄧㄢˋ', pinyin: 'shǎndiàn', name: 'ㄕㄢˇ ㄉㄧㄢˋ (shǎndiàn)', category: 'vocabulary', example: '電', phrase: '閃電', hint: '閃電 (Lightning)', audioText: '閃電' },
{ symbol: 'ㄘㄠˇ ㄏㄨㄥˊ', pinyin: 'cǎihóng', name: 'ㄘㄠˇ ㄏㄨㄥˊ (cǎihóng)', category: 'vocabulary', example: '虹', phrase: '彩虹', hint: '彩虹 (Rainbow)', audioText: '彩虹' },
{ symbol: 'ㄉㄚˋ ㄏㄞˇ', pinyin: 'dàhǎi', name: 'ㄉㄚˋ ㄏㄞˇ (dàhǎi)', category: 'vocabulary', example: '海', phrase: '大海', hint: '大海 (Sea / Ocean)', audioText: '大海' },
{ symbol: 'ㄍㄠ ㄕㄢ', pinyin: 'gāoshān', name: 'ㄍㄠ ㄕㄢ (gāoshān)', category: 'vocabulary', example: '山', phrase: '高山', hint: '高山 (Mountain)', audioText: '高山' },
{ symbol: 'ㄙㄣ ㄌㄧㄣˊ', pinyin: 'sēnlín', name: 'ㄙㄣ ㄌㄧㄣˊ (sēnlín)', category: 'vocabulary', example: '林', phrase: '森林', hint: '森林 (Forest)', audioText: '森林' },
{ symbol: 'ㄏㄨㄚ ㄉㄨㄛˇ', pinyin: 'huāduǒ', name: 'ㄏㄨㄚ ㄉㄨㄛˇ (huāduǒ)', category: 'vocabulary', example: '花', phrase: '花朵', hint: '花朵 (Flower)', audioText: '花朵' },
{ symbol: 'ㄘㄠˇ ㄉㄧˋ', pinyin: 'cǎodì', name: 'ㄘㄠˇ ㄉㄧˋ (cǎodì)', category: 'vocabulary', example: '草', phrase: '草地', hint: '草地 (Grassland)', audioText: '草地' },
{ symbol: 'ㄕㄨˋ ㄇㄨˋ', pinyin: 'shùmù', name: 'ㄕㄨˋ ㄇㄨˋ (shùmù)', category: 'vocabulary', example: '樹', phrase: '樹木', hint: '樹木 (Tree)', audioText: '樹木' },
{ symbol: 'ㄕˊ ㄊㄡ˙', pinyin: 'shítou', name: 'ㄕˊ ㄊㄡ˙ (shítou)', category: 'vocabulary', example: '石', phrase: '石頭', hint: '石頭 (Stone / Rock)', audioText: '石頭' },
{ symbol: 'ㄕㄚ ㄊㄢ', pinyin: 'shātān', name: 'ㄕㄚ ㄊㄢ (shātān)', category: 'vocabulary', example: '沙', phrase: '沙灘', hint: '沙灘 (Beach)', audioText: '沙灘' },
{ symbol: 'ㄕㄨˋ ㄧㄝˋ', pinyin: 'shùyè', name: 'ㄕㄨˋ ㄧㄝˋ (shùyè)', category: 'vocabulary', example: '葉', phrase: '樹葉', hint: '樹葉 (Leaf)', audioText: '樹葉' },
{ symbol: 'ㄋㄧˊ ㄊㄨˇ', pinyin: 'nítǔ', name: 'ㄋㄧˊ ㄊㄨˇ (nítǔ)', category: 'vocabulary', example: '泥', phrase: '泥土', hint: '泥土 (Soil / Mud)', audioText: '泥土' },
{ symbol: 'ㄏㄨㄥˊ ㄙㄜˋ', pinyin: 'hóngsè', name: 'ㄏㄨㄥˊ ㄙㄜˋ (hóngsè)', category: 'vocabulary', example: '紅', phrase: '紅色', hint: '紅色 (Red)', audioText: '紅色' },
{ symbol: 'ㄌㄢˊ ㄙㄜˋ', pinyin: 'lánsè', name: 'ㄌㄢˊ ㄙㄜˋ (lánsè)', category: 'vocabulary', example: '藍', phrase: '藍色', hint: '藍色 (Blue)', audioText: '藍色' },
{ symbol: 'ㄏㄨㄤˊ ㄙㄜˋ', pinyin: 'huángsè', name: 'ㄏㄨㄤˊ ㄙㄜˋ (huángsè)', category: 'vocabulary', example: '黃', phrase: '黃色', hint: '黃色 (Yellow)', audioText: '黃色' },
{ symbol: 'ㄌㄩˋ ㄙㄜˋ', pinyin: 'lǜsè', name: 'ㄌㄩˋ ㄙㄜˋ (lǜsè)', category: 'vocabulary', example: '綠', phrase: '綠色', hint: '綠色 (Green)', audioText: '綠色' },
{ symbol: 'ㄏㄟ ㄙㄜˋ', pinyin: 'hēisè', name: 'ㄏㄟ ㄙㄜˋ (hēisè)', category: 'vocabulary', example: '黑', phrase: '黑色', hint: '黑色 (Black)', audioText: '黑色' },
{ symbol: 'ㄅㄞˊ ㄙㄜˋ', pinyin: 'báisè', name: 'ㄅㄞˊ ㄙㄜˋ (báisè)', category: 'vocabulary', example: '白', phrase: '白色', hint: '白色 (White)', audioText: '白色' },
{ symbol: 'ㄗˇ ㄙㄜˋ', pinyin: 'zǐsè', name: 'ㄗˇ ㄙㄜˋ (zǐsè)', category: 'vocabulary', example: '紫', phrase: '紫色', hint: '紫色 (Purple)', audioText: '紫色' },
{ symbol: 'ㄈㄣˇ ㄏㄨㄥˊ ㄙㄜˋ', pinyin: 'fěnhóngsè', name: 'ㄈㄣˇ ㄏㄨㄥˊ ㄙㄜˋ (fěnhóngsè)', category: 'vocabulary', example: '粉', phrase: '粉紅色', hint: '粉紅色 (Pink)', audioText: '粉紅色' },
{ symbol: 'ㄐㄩˊ ㄙㄜˋ', pinyin: 'júsè', name: 'ㄐㄩˊ ㄙㄜˋ (júsè)', category: 'vocabulary', example: '橘', phrase: '橘色', hint: '橘色 (Orange)', audioText: '橘色' },
{ symbol: 'ㄧㄢˇ ㄐㄧㄥ', pinyin: 'yǎnjīng', name: 'ㄧㄢˇ ㄐㄧㄥ (yǎnjīng)', category: 'vocabulary', example: '眼', phrase: '眼睛', hint: '眼睛 (Eye)', audioText: '眼睛' },
{ symbol: 'ㄦˇ ㄉㄨㄛ˙', pinyin: 'ěrduo', name: 'ㄦˇ ㄉㄨㄛ˙ (ěrduo)', category: 'vocabulary', example: '耳', phrase: '耳朵', hint: '耳朵 (Ear)', audioText: '耳朵' },
{ symbol: 'ㄅㄧˊ ㄗ˙', pinyin: 'bízi', name: 'ㄅㄧˊ ㄗ˙ (bízi)', category: 'vocabulary', example: '鼻', phrase: '鼻子', hint: '鼻子 (Nose)', audioText: '鼻子' },
{ symbol: 'ㄗㄨㄟˇ ㄅㄚ', pinyin: 'zuǐbā', name: 'ㄗㄨㄟˇ ㄅㄚ (zuǐbā)', category: 'vocabulary', example: '嘴', phrase: '嘴巴', hint: '嘴巴 (Mouth)', audioText: '嘴巴' },
{ symbol: 'ㄊㄡˊ ㄈㄚˇ', pinyin: 'tóufǎ', name: 'ㄊㄡˊ ㄈㄚˇ (tóufǎ)', category: 'vocabulary', example: '頭', phrase: '頭髮', hint: '頭髮 (Hair)', audioText: '頭髮' },
{ symbol: 'ㄕㄨㄤ ㄕㄡˇ', pinyin: 'shuāngshǒu', name: 'ㄕㄨㄤ ㄕㄡˇ (shuāngshǒu)', category: 'vocabulary', example: '手', phrase: '雙手', hint: '雙手 (Hands)', audioText: '雙手' },
{ symbol: 'ㄕㄨㄤ ㄐㄧㄠˇ', pinyin: 'shuāngjiǎo', name: 'ㄕㄨㄤ ㄐㄧㄠˇ (shuāngjiǎo)', category: 'vocabulary', example: '腳', phrase: '雙腳', hint: '雙腳 (Feet)', audioText: '雙腳' },
{ symbol: 'ㄐㄧㄢ ㄅㄤˇ', pinyin: 'jiānbǎng', name: 'ㄐㄧㄢ ㄅㄤˇ (jiānbǎng)', category: 'vocabulary', example: '肩', phrase: '肩膀', hint: '肩膀 (Shoulder)', audioText: '肩膀' },
{ symbol: 'ㄧㄚˊ ㄔˇ', pinyin: 'yáchǐ', name: 'ㄧㄚˊ ㄔˇ (yáchǐ)', category: 'vocabulary', example: '牙', phrase: '牙齒', hint: '牙齒 (Tooth / Teeth)', audioText: '牙齒' },
{ symbol: 'ㄍㄨㄥ ㄩㄢˊ', pinyin: 'gōngyuán', name: 'ㄍㄨㄥ ㄩㄢˊ (gōngyuán)', category: 'vocabulary', example: '公', phrase: '公園', hint: '公園 (Park)', audioText: '公園' },
{ symbol: 'ㄔㄠ ㄕㄤ', pinyin: 'chāoshāng', name: 'ㄔㄠ ㄕㄤ (chāoshāng)', category: 'vocabulary', example: '超', phrase: '超商', hint: '超商 (Convenience Store)', audioText: '超商' },
{ symbol: 'ㄧ ㄩㄢˋ', pinyin: 'yīyuàn', name: 'ㄧ ㄩㄢˋ (yīyuàn)', category: 'vocabulary', example: '醫', phrase: '醫院', hint: '醫院 (Hospital)', audioText: '醫院' },
{ symbol: 'ㄧㄡˊ ㄐㄩˊ', pinyin: 'yóujú', name: 'ㄧㄡˊ ㄐㄩˊ (yóujú)', category: 'vocabulary', example: '郵', phrase: '郵局', hint: '郵局 (Post Office)', audioText: '郵局' },
{ symbol: 'ㄧㄣˊ ㄏㄤˊ', pinyin: 'yínháng', name: 'ㄧㄣˊ ㄏㄤˊ (yínháng)', category: 'vocabulary', example: '銀', phrase: '銀行', hint: '銀行 (Bank)', audioText: '銀行' },
{ symbol: 'ㄊㄨˊ ㄕㄨ ㄍㄨㄢˇ', pinyin: 'túshūguǎn', name: 'ㄊㄨˊ ㄕㄨ ㄍㄨㄢˇ (túshūguǎn)', category: 'vocabulary', example: '圖', phrase: '圖書館', hint: '圖書館 (Library)', audioText: '圖書館' },
{ symbol: 'ㄉㄨㄥˋ ㄨˋ ㄩㄢˊ', pinyin: 'dòngwùyuán', name: 'ㄉㄨㄥˋ ㄨˋ ㄩㄢˊ (dòngwùyuán)', category: 'vocabulary', example: '動', phrase: '動物園', hint: '動物園 (Zoo)', audioText: '動物園' },
{ symbol: 'ㄧㄡˊ ㄌㄜˋ ㄩㄢˊ', pinyin: 'yóulèyuán', name: 'ㄧㄡˊ ㄌㄜˋ ㄩㄢˊ (yóulèyuán)', category: 'vocabulary', example: '遊', phrase: '遊樂園', hint: '遊樂園 (Amusement Park)', audioText: '遊樂園' },
{ symbol: 'ㄘㄢ ㄊㄧㄥ', pinyin: 'cāntīng', name: 'ㄘㄢ ㄊㄧㄥ (cāntīng)', category: 'vocabulary', example: '餐', phrase: '餐廳', hint: '餐廳 (Restaurant)', audioText: '餐廳' },
{ symbol: 'ㄔㄨˊ ㄈㄤˊ', pinyin: 'chúfáng', name: 'ㄔㄨˊ ㄈㄤˊ (chúfáng)', category: 'vocabulary', example: '廚', phrase: '廚房', hint: '廚房 (Kitchen)', audioText: '廚房' },
{ symbol: 'ㄎㄜˋ ㄊㄧㄥ', pinyin: 'kètīng', name: 'ㄎㄜˋ ㄊㄧㄥ (kètīng)', category: 'vocabulary', example: '客', phrase: '客廳', hint: '客廳 (Living Room)', audioText: '客廳' },
{ symbol: 'ㄨㄛˋ ㄕˋ', pinyin: 'wòshì', name: 'ㄨㄛˋ ㄕˋ (wòshì)', category: 'vocabulary', example: '臥', phrase: '臥室', hint: '臥室 (Bedroom)', audioText: '臥室' },
{ symbol: 'ㄩˋ ㄕˋ', pinyin: 'yùshì', name: 'ㄩˋ ㄕˋ (yùshì)', category: 'vocabulary', example: '浴', phrase: '浴室', hint: '浴室 (Bathroom)', audioText: '浴室' },
{ symbol: 'ㄎㄨㄞˋ ㄌㄜˋ', pinyin: 'kuàilè', name: 'ㄎㄨㄞˋ ㄌㄜˋ (kuàilè)', category: 'vocabulary', example: '快', phrase: '快樂', hint: '快樂 (Happy)', audioText: '快樂' },
{ symbol: 'ㄕㄥ ㄑㄧˋ', pinyin: 'shēngqì', name: 'ㄕㄥ ㄑㄧˋ (shēngqì)', category: 'vocabulary', example: '生', phrase: '生氣', hint: '生氣 (Angry)', audioText: '生氣' },
{ symbol: 'ㄕㄤ ㄒㄧㄣ', pinyin: 'shāngxīn', name: 'ㄕㄤ ㄒㄧㄣ (shāngxīn)', category: 'vocabulary', example: '傷', phrase: '傷心', hint: '傷心 (Sad)', audioText: '傷心' },
{ symbol: 'ㄏㄞˋ ㄆㄚˋ', pinyin: 'hàipà', name: 'ㄏㄞˋ ㄆㄚˋ (hàipà)', category: 'vocabulary', example: '害', phrase: '害怕', hint: '害怕 (Scared)', audioText: '害怕' },
{ symbol: 'ㄒㄧˇ ㄏㄨㄢ', pinyin: 'xǐhuān', name: 'ㄒㄧˇ ㄏㄨㄢ (xǐhuān)', category: 'vocabulary', example: '喜', phrase: '喜歡', hint: '喜歡 (Like)', audioText: '喜歡' },
{ symbol: 'ㄒㄧㄝˋ ㄒㄧㄝ˙', pinyin: 'xièxie', name: 'ㄒㄧㄝˋ ㄒㄧㄝ˙ (xièxie)', category: 'vocabulary', example: '謝', phrase: '謝謝', hint: '謝謝 (Thank you)', audioText: '謝謝' },
{ symbol: 'ㄉㄨㄟˋ ㄅㄨˋ ㄑㄧˇ', pinyin: 'duìbùqǐ', name: 'ㄉㄨㄟˋ ㄅㄨˋ ㄑㄧˇ (duìbùqǐ)', category: 'vocabulary', example: '對', phrase: '對不起', hint: '對不起 (Sorry)', audioText: '對不起' },
{ symbol: 'ㄗㄠˇ ㄢ', pinyin: 'zǎoān', name: 'ㄗㄠˇ ㄢ (zǎoān)', category: 'vocabulary', example: '早', phrase: '早安', hint: '早安 (Good morning)', audioText: '早安' },
{ symbol: 'ㄨㄢˇ ㄢ', pinyin: 'wǎnān', name: 'ㄨㄢˇ ㄢ (wǎnān)', category: 'vocabulary', example: '晚', phrase: '晚安', hint: '晚安 (Good night)', audioText: '晚安' },
{ symbol: 'ㄔㄨㄣ ㄊㄧㄢ', pinyin: 'chūntiān', name: 'ㄔㄨㄣ ㄊㄧㄢ (chūntiān)', category: 'vocabulary', example: '春', phrase: '春天', hint: '春天 (Spring)', audioText: '春天' },
{ symbol: 'ㄒㄧㄚˋ ㄊㄧㄢ', pinyin: 'xiàtiān', name: 'ㄒㄧㄚˋ ㄊㄧㄢ (xiàtiān)', category: 'vocabulary', example: '夏', phrase: '夏天', hint: '夏天 (Summer)', audioText: '夏天' },
{ symbol: 'ㄑㄧㄡ ㄊㄧㄢ', pinyin: 'qiūtiān', name: 'ㄑㄧㄡ ㄊㄧㄢ (qiūtiān)', category: 'vocabulary', example: '秋', phrase: '秋天', hint: '秋天 (Autumn)', audioText: '秋天' },
{ symbol: 'ㄉㄨㄥ ㄊㄧㄢ', pinyin: 'dōngtiān', name: 'ㄉㄨㄥ ㄊㄧㄢ (dōngtiān)', category: 'vocabulary', example: '冬', phrase: '冬天', hint: '冬天 (Winter)', audioText: '冬天' },
{ symbol: 'ㄇㄠˋ ㄗ˙', pinyin: 'màozi', name: 'ㄇㄠˋ ㄗ˙ (màozi)', category: 'vocabulary', example: '帽', phrase: '帽子', hint: '帽子 (Hat / Cap)', audioText: '帽子' },
{ symbol: 'ㄒㄧㄝˊ ㄗ˙', pinyin: 'xiézi', name: 'ㄒㄧㄝˊ ㄗ˙ (xiézi)', category: 'vocabulary', example: '鞋', phrase: '鞋子', hint: '鞋子 (Shoes)', audioText: '鞋子' },
{ symbol: 'ㄨㄚˋ ㄗ˙', pinyin: 'wàzi', name: 'ㄨㄚˋ ㄗ˙ (wàzi)', category: 'vocabulary', example: '襪', phrase: '襪子', hint: '襪子 (Socks)', audioText: '襪子' },
{ symbol: 'ㄕㄡˇ ㄊㄠˋ', pinyin: 'shǒutào', name: 'ㄕㄡˇ ㄊㄠˋ (shǒutào)', category: 'vocabulary', example: '手', phrase: '手套', hint: '手套 (Gloves)', audioText: '手套' },
{ symbol: 'ㄨㄟˊ ㄐㄧㄣ', pinyin: 'wéijīn', name: 'ㄨㄟˊ ㄐㄧㄣ (wéijīn)', category: 'vocabulary', example: '圍', phrase: '圍巾', hint: '圍巾 (Scarf)', audioText: '圍巾' },
{ symbol: 'ㄎㄨˋ ㄗ˙', pinyin: 'kùzi', name: 'ㄎㄨˋ ㄗ˙ (kùzi)', category: 'vocabulary', example: '褲', phrase: '褲子', hint: '褲子 (Pants / Trousers)', audioText: '褲子' },
{ symbol: 'ㄑㄩㄣˊ ㄗ˙', pinyin: 'qúnzi', name: 'ㄑㄩㄣˊ ㄗ˙ (qúnzi)', category: 'vocabulary', example: '裙', phrase: '裙子', hint: '裙子 (Skirt / Dress)', audioText: '裙子' },
{ symbol: 'ㄨㄞˋ ㄊㄠˋ', pinyin: 'wàitào', name: 'ㄨㄞˋ ㄊㄠˋ (wàitào)', category: 'vocabulary', example: '外', phrase: '外套', hint: '外套 (Coat / Jacket)', audioText: '外套' },
{ symbol: 'ㄨㄢˊ ㄐㄩˋ', pinyin: 'wánjù', name: 'ㄨㄢˊ ㄐㄩˋ (wánjù)', category: 'vocabulary', example: '玩', phrase: '玩具', hint: '玩具 (Toy)', audioText: '玩具' },
{ symbol: 'ㄧㄤˊ ㄨㄚˊ ㄨㄚ˙', pinyin: 'yángwáwa', name: 'ㄧㄤˊ ㄨㄚˊ ㄨㄚ˙ (yángwáwa)', category: 'vocabulary', example: '娃', phrase: '洋娃娃', hint: '洋娃娃 (Doll)', audioText: '洋娃娃' },
{ symbol: 'ㄐㄧ ㄇㄨˋ', pinyin: 'jīmù', name: 'ㄐㄧ ㄇㄨˋ (jīmù)', category: 'vocabulary', example: '積', phrase: '積木', hint: '積木 (Blocks)', audioText: '積木' },
{ symbol: 'ㄑㄧㄡˊ ㄒㄧㄝˊ', pinyin: 'qiúxié', name: 'ㄑㄧㄡˊ ㄒㄧㄝˊ (qiúxié)', category: 'vocabulary', example: '球', phrase: '球鞋', hint: '球鞋 (Sneakers)', audioText: '球鞋' },
{ symbol: 'ㄈㄥ ㄓㄥ', pinyin: 'fēngzhēng', name: 'ㄈㄥ ㄓㄥ (fēngzhēng)', category: 'vocabulary', example: '風', phrase: '風箏', hint: '風箏 (Kite)', audioText: '風箏' },
{ symbol: 'ㄆㄧㄣ ㄊㄨˊ', pinyin: 'pīntú', name: 'ㄆㄧㄣ ㄊㄨˊ (pīntú)', category: 'vocabulary', example: '拼', phrase: '拼圖', hint: '拼圖 (Puzzle)', audioText: '拼圖' }
];